### ISSUE TITLE
不渲染 ，控制台输出： effect did-mount

### ISSUE THREAD

**Issue by xl619419059** [antvis/graphin#10]
**Describe the bug**
不渲染 ，控制台输出： effect did-mount
**To Reproduce**

// Add Code Sanbox reproduce link using this template: https://codesandbox.io/s/data-driven-3o71b

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [ chrome]
 - Version [1.0.0]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pomelo-nwu** [comment]
可能是codesandbox每次打开要下载npm依赖，速度会有点慢，我这边是okay的。
![image](https://user-images.githubusercontent.com/10703060/69472492-f1958000-0de5-11ea-943b-b4927d87e301.png)
为方便用户查看，我们后续会将codesandbox和examples仓库结合，详情参考ISSUE：https://github.com/antvis/graphin/issues/9

**Comment by zxc0328** [comment]
可能是没有引入 CSS

```
import "@antv/graphin/dist/index.css";
```

之前的快速开始中的 CodePen 链接不是最新的，请使用这个：

https://codesandbox.io/s/data-driven-fkue0

**Comment by zxc0328** [comment]
先关了，如果有问题可以再打开。
