### ISSUE TITLE
官网中的示例代码

### ISSUE THREAD

**Issue by CrazyOctopusDan** [antvis/Graphin#100]
Graphin 核心概念 => Data 数据驱动 => 02 代码里 
![image](https://user-images.githubusercontent.com/18019209/80565179-6a96a480-8a22-11ea-8650-e77764b33778.png)

`transform.(data)`这个用法应该是手滑了？
```
return {
        nodes: transform.nodes(data.nodes),
        edges: transform.edges(data.edges),
    };
```
这样会报错的“transform.nodes is not a function”
既然是在一个作用域内，或许这么写 `nodes: nodes(data.nodes)`也挺好？

**Comment by pomelo-nwu** [comment]
https://github.com/antvis/Graphin/commit/278127573582eb612cadcdd6e09ba78e25c6eca6 谢谢提出，已修改
