### ISSUE TITLE
好像是react 的项目，后期会支持vue吗

### ISSUE THREAD

**Issue by fitan** [antvis/graphin#12]

**Comment by pomelo-nwu** [comment]
你好，首先感谢你关注graphin项目，graphin是业务同学孵化出来的项目，因此时间和精力有限，目前只支持React框架，后续也不太考虑支持Vue框架，如果你感兴趣，可以Fork项目，基于Vue与G6再造一个Graphin-Vue版本，我们也会尽我们所能提供Graphin相关设计文档，比如我们在FAQ上提供了与框架无关的产品设计文档：https://graphin.antv.vision/zh/docs/manual/FAQ ， 欢迎一起讨论

**Comment by Yankj** [comment]
那是不是可以考虑出个在vue中的引用graphin react文档？

**Comment by pomelo-nwu** [comment]
> 那是不是可以考虑出个在vue中的引用graphin react文档？

Graphin的技术实现是基于G6做的React组件，不支持在Vue中引入。除非 ...搞个微前端？或者给个独立app节点挂载运行？

**Comment by Yankj** [comment]
是的，vue项目这样的需求很强烈

**Comment by zxc0328** [comment]
https://viserjs.github.io/demo.html#/viserGraph/g6/basic-graph 可以看一下 Viser-graph。不过可能那边投入的人力比较少。也可以参与一起建设  https://github.com/viserjs/viser/issues/419

**Comment by lloydzhou** [comment]
有写一个vue的版本：[graphin-vue](https://github.com/lloydzhou/graphin-vue) （欢迎大家一起贡献代码，希望能及时跟上主库的版本）

1. 直接使用@antv/graphin内置的shape和layout逻辑代码
> 这样只要跟着主库升级就能升级使用最新的核心代码逻辑
> 也能避免大量的改写工作可能引入新的bug的风险
3. 使用vue重写ui组件以及behaviors组件
> 只重新UI组件，也能减少改写的工作量

PS: 改写的库，编译的时候移除react的依赖
#370
