### ISSUE TITLE
Ref 实例类型问题

### ISSUE THREAD

**Issue by Bubbleinpit** [antvis/Graphin#123]
**Describe the bug**

如果我指定 Ref 实例的类型为 Graphin 中定义的 GraphType 的话，lint 将报错：不能将类型“RefObject<{ graph: GraphType; }>”分配给类型“string | ((instance: Graph | null) => void) | RefObject<Graph> | null | undefined”。

并且，Graphin 导出的类型，无论是 G6 的 Graph 还是 Graphin 再次继承的 GraphType，都没有 off 这个属性：Property 'off' does not exist on type 'GraphType'，Property 'off' does not exist on type 'Graph'。

这两个问题在下面的例子中都可以得到复现。

**To Reproduce**

https://codesandbox.io/s/optimistic-bhabha-sc8zc

**Expected behavior**

类型定义需要更新，至少将暴露出的 API 都进行补全。

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 1.2.1 / 1.2.0

**Comment by pomelo-nwu** [comment]
是的，之前类型这块确实做的不好，我们近期在升级G6的版本，新的版本会解决这些问题
