### ISSUE TITLE
graph.setItemState(item, 'state', true) not updating item state

### ISSUE THREAD

**Issue by peironggg** [antvis/Graphin#126]
**Describe the bug**
In the React hook useEffect, I attached a listener to listen for the event when the mouse enters the node. When it does so, it will call a function which sets the node's 'highlighted' state to true and prints the node. However, the state of the node is not updated when it is printed. I am trying to replicate the example code at https://g6.antv.vision/zh/examples/interaction/highlight#highlightDark which highlights the node when the mouse hovers over it. I am using the Graphin library. I have attached some pictures and the console output to make it easier to replicate.

**Desktop (please complete the following information):**
 - OS: [macOS Catalina]
 - Browser [chrome]
 - Version [81.0.4044.138]

<img width="894" alt="Screenshot 2020-05-15 at 7 46 52 PM" src="https://user-images.githubusercontent.com/35712975/82047618-ae0d3600-96e5-11ea-9e58-fe3ad8b226fe.png">
<img width="399" alt="Screenshot 2020-05-15 at 7 47 36 PM" src="https://user-images.githubusercontent.com/35712975/82047624-b1a0bd00-96e5-11ea-8156-33c48b6acfcf.png">
<img width="372" alt="Screenshot 2020-05-15 at 7 47 47 PM" src="https://user-images.githubusercontent.com/35712975/82047625-b1a0bd00-96e5-11ea-8cb0-bc5ead5ee186.png">

**Comment by pomelo-nwu** [comment]
Because the highlight state name of graphin is inconsistent with that of G6, the light of Graphin is "highlight.light", dark is "highlight.dark", this is unified in the next version, the correct code in sandcodebox：https://codesandbox.io/s/hopeful-ptolemy-cnriq?file=/index.jsx

**Comment by peironggg** [comment]
Okay thank you!

**Comment by peironggg** [comment]
Can I check when the updated docs for Graphin will be released? There are some functionalities such as updating the data model of the edge, etc that I refer to G6's documentation but does not seem to work for Graphin.

**Comment by peironggg** [comment]
Hi, just wanna ask if my edge's shape is not line ('quadratic' or something else), the highlight.light and highlight.dark state will no longer work?
