### ISSUE TITLE
ContextMenu 无法获取当前节点

### ISSUE THREAD

**Issue by caoyi0905** [antvis/Graphin#127]
**Describe the bug**
ContextMenu 在某个未选中的 node 上右键，识别出来的node是有误的，因为当前右键的 node 的状态并不是'selected'。有什么办法在 ContextMenu 的 onClick 函数中获取当前右键的节点？

bug 在 [官网的例子](https://graphin.antv.vision/zh/examples/components/contextmenu) 就可以复现。先选中 node-2，再在 node-0 上右键点 delete，识别出来是 node-2。
![image](https://user-images.githubusercontent.com/8458441/82052715-b1f18600-96ee-11ea-9ffa-9677f5ec144c.png)

**Comment by pomelo-nwu** [comment]
@caoyi0905 ContextMenu是一个辅助用户操作的组件，因此对于节点右键选择，我们考虑了多选的情况（比如圈选或多选后右键菜单进行批处理），先选中节点，再右键菜单，当然如果只考虑单选，可以自己监听这个"node:contextmenu"事件进行逻辑处理
` const graphinRef = React.createRef();
  React.useEffect(() => {
    graphinRef.current.graph.on("node:contextmenu", e => {
      message.info(`oh ${e.item.get("id")}`);
      console.log(e);
    });
  }, []);`
详见codesandbox：https://codesandbox.io/s/hopeful-cohen-0phjj?file=/index.jsx:525-734

**Comment by caoyi0905** [comment]
非常感谢！
