### ISSUE TITLE
3.0.7版本edge设置shape: "polyline"无效

### ISSUE THREAD

**Issue by zuolinya** [antvis/Graphin#13]
3.0.7版本edge设置shape: "polyline"无效，另外npm install 直接给默认了一个^3.0.7-beta.1，目前稳定的版本是哪个

**Comment by pomelo-nwu** [comment]
graphin现在依赖G6的版本是3.1.9 . 我刚用codesandbox测试了下：https://codesandbox.io/s/quirky-thompson-352xw 。shape为` cubic ,quadratic, arc`为正常shape，有问题的shape 为`loop polyline` 。我们这边尽快定位下问题

**Comment by pomelo-nwu** [comment]
@baizn 聚则哥，帮忙看下G6的问题

**Comment by baizn** [comment]
3.0.7 还没有 polyline 类型，这个是3.1.0以后才加的。

**Comment by zuolinya** [comment]
更新到了3.2.1，这个属性生效了，但是添加 linkCenter: true,direction: "LR",线只是位置都到上面了，错乱了。

**Comment by zxc0328** [comment]
> 更新到了3.2.1，这个属性生效了，但是添加 linkCenter: true,direction: "LR",线只是位置都到上面了，错乱了。

这个问题可以去 G6 提 issue，带上复现的 CodeSandbox 就可以。这边先关了。
