### ISSUE TITLE
我在umi3项目中引用并且使用了@antv/graphin，结果打包时体积太大过不了

### ISSUE THREAD

**Issue by CrazyOctopusDan** [antvis/Graphin#134]
如题的问题；
由于项目需要，我使用了咱们antv/graphin的包，使用方式如官网=>快速上手所示
```
import GraphIn from '@antv/graphin'
```
结果在build的时候检测到有一个文件超大了
![image](https://user-images.githubusercontent.com/18019209/83134344-cbdf8f80-a116-11ea-997a-728d723574f7.png)
被强制勒令
![image](https://user-images.githubusercontent.com/18019209/83134525-13feb200-a117-11ea-9f62-c1aaa9d29932.png)

于是乎我想到了之前使用antd时候的按需加载，使用了babel-plugin-import

但是又发生了奇异的变化↓
![image](https://user-images.githubusercontent.com/18019209/83134812-7e175700-a117-11ea-8666-93f9df583b5e.png)

我就去查看node_modules中的antv/graphin代码，发现目录结构中只有一个dist，项目整体被全部打包在其中了。 

解决方案现在变成只能把这个包扔在cdn上面再用，不然打包怎么着都过不去。

不知道这种情况是否有解决方案？或者优化空间？

**Comment by pomelo-nwu** [comment]
打包现在采用babel打包，产出 lib，esm。至于 external 出去需要给浏览器用，已经用webpack打包产生umd产物。Graphin2.0做了架构大调整，原先的字体文件也单独拆包：https://github.com/antvis/Graphin/tree/master/packages/graphin-icons/src 
 ，工具函数也不再引入lodash等。Graphin-Component将不再依赖其他UI组件库，体积问题我们还在进一步优化中。
