### ISSUE TITLE
在graphin中使用G6插件miniMap的问题

### ISSUE THREAD

**Issue by lailailai1203** [antvis/Graphin#148]
我在使用G6插件miniMap过程中,发现graphin中内置的六边形节点HexagonNode会导致miniMap失效.
问题原因:可能是在制作HexagonNode过程中,在制作selected的图形时,指定point为[]导致.

**Comment by pomelo-nwu** [comment]
@lailailai1203 试下Graphin2.0提供的MiniMap：https://graphin.antv.vision/components/interaction/mini-map
