### ISSUE TITLE
关于右键菜单的一个小BUG

### ISSUE THREAD

**Issue by hardyfan** [antvis/Graphin#149]
我用edge最新的浏览器，调试Graphin的示例代码（https://codesandbox.io/s/graphin-components-context-menu-tgpkb?from-embed=&file=/src/styles.css:0-75）时发现一个问题：点击右键菜单时会先弹出浏览器自带的右键菜单。由于配置的代码仅仅是JSX语法的：
`<Graphin data={data}> 
    <ContextMenu options={options} /> 
</Graphin>`

无法对事件进行阻止。建议在实现的代码里，对右键菜单里增加对默认事件的阻止代码：
`e.preventDefault()`

**Comment by pomelo-nwu** [comment]
这个问题已修复，详见[PR](https://github.com/antvis/Graphin/commit/f4c4df8a8f1063f773c33a3deb6bd37afd8bbafa)，请更新graphin-components@1.4.1版本，因为同时也升级了antd的依赖库，iconType请用ant-design/icons,效果如下:
![image](https://user-images.githubusercontent.com/10703060/84553127-bb016180-ad45-11ea-9d0e-ffd5d05fe2e7.png)
