### ISSUE TITLE
想在react15.x的项目中使用，发现底层graphin包依赖react16里的Fragment，请问能否删除？

### ISSUE THREAD

**Issue by xwzpp** [antvis/Graphin#15]
**Describe the bug**
想在react15.x的项目中使用，发现底层graphin包依赖react16里的Fragment，请问能否删除？底层包应该尽可能没有对react版本特性的依赖。

**To Reproduce**
![image](https://user-images.githubusercontent.com/7036549/69737972-4895af00-1170-11ea-8267-6556531a7734.png)

编译完会有Fragment的依赖：
![image](https://user-images.githubusercontent.com/7036549/69738029-6105c980-1170-11ea-8866-35ab4b8079ae.png)

**Comment by pomelo-nwu** [comment]
你好，Graphin未来的开发需要ReactHook等特性，在graphin-components中的组件都是用hook去编写的，因此不止你上文提的这一个Fragment问题。建议你在项目里也升级React版本，以此享受版本更新带来的生态好处。升级指南：https://juejin.im/entry/59d707cef265da0653530ff5

**Comment by xwzpp** [comment]
好的，那我参考指南升级下react版本，谢谢，期待后续Graphin的发展！

**Comment by pomelo-nwu** [comment]
> 好的，那我参考指南升级下react版本，谢谢，期待后续Graphin的发展！
好的，谢谢，我们刚开通了钉钉交流群，有空可以一起交流学习：https://github.com/antvis/Graphin#dingtalk
