### ISSUE TITLE
快速开始的演示示例白屏

### ISSUE THREAD

**Issue by az674lqs** [antvis/Graphin#153]
必须覆写.graphin-core样式，给个高度才能显示出来，不然高度就是0

**Comment by pomelo-nwu** [comment]
非常抱歉这么晚回复你，css需要单独引入，1.x版本的css样式是单独打包的，需要手动引入`import '@antv/graphin/dist/inedx.css'`

**Comment by pomelo-nwu** [comment]
@az674lqs graphin2.0有了新的文档，欢迎使用：https://graphin.antv.vision/
