### ISSUE TITLE
style样式引入问题

### ISSUE THREAD

**Issue by 520203xuxia** [antvis/Graphin#154]
文档中引入样式使用：import '@antv/graphin/dist/index.css';

但是webpack打包过程中 mode=production情况下，tree-shaking过程会把引入的样式去掉，导致样式丢失。

看了下package.json的sideEffects配置项为false，跟这个配置项有关。

**Comment by pomelo-nwu** [comment]
这个和你项目的webpack配置有关，graphin本身是纯ES Module的包，所以配置sideEffects为false没有问题，但是你项目引入的时候，为了防止webpack tree shaking 将其css删除，你需要自己配置下。
![Uploading image.png…]()
也可以参考graphin-studio的配置：https://github.com/antvis/Graphin/blob/master/packages/graphin-studio/webpack.config.js#L55
