### ISSUE TITLE
请问可以自定义style内的颜色吗

### ISSUE THREAD

**Issue by yangjiao2** [antvis/Graphin#155]
**Is your feature request related to a problem? Please describe.**
初学g6，想问下可否用任何方法修改
1. canvas 的背景色
2. node 节点的背景色有渐层过滤

**Describe the solution you'd like**
example: 
linear-gradient(163deg, #84f0ff 12%, rgba(255, 255, 255, 0) 88%);

**Comment by pomelo-nwu** [comment]
1. canvas是一个DOM，你可以直接修改styles.background背景色，或者在外层dom设置background都行
2.G6的设置背景色有教程的：https://g6.antv.vision/zh/docs/manual/FAQ/gradient/#gatsby-focus-wrapper，其底层@antv/g也是依照[MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/createLinearGradient)的API实现的。

**Comment by yangjiao2** [comment]
谢谢～
