### ISSUE TITLE
200 个节点 200个边就卡死了

### ISSUE THREAD

**Issue by iventong** [antvis/Graphin#156]
设置随机扩展关系由原来的 5变为50
 然后扩展4次 界面就卡死了。
已经开启GPU 渲染。

可进行验证

**Comment by baizn** [comment]
提供一个在线demo，看下是不是哪里使用的不太合适，目前几千节点的数据量下都不会卡的  https://g6.antv.vision/zh/examples/performance/perf

**Comment by iventong** [comment]
https://codesandbox.io/s/dry-river-80o53
修改100 节点可感觉有卡顿 
200 就卡的无法接受了
这个问题在群内确认过这个问题。但是目前么有修复

**Comment by baizn** [comment]
做什么操作呢？ 拖动、选中等操作还是挺流畅啊， 另外 graphin 的问题来这个仓库里面提：https://github.com/antvis/Graphin

**Comment by pomelo-nwu** [comment]
@iventong Graphin2.0做了一些性能优化，200节点200边现在应该不会卡了。但是超过500节点的力导还是会卡，超过1000节点的渲染，依旧会卡。这个问题我们在想办法解决，交互优化是一种方式，参考：https://graphin.antv.vision/graphin/behaviors/behaviors 在拖拽和缩放的时候仅展示keyshape，即显示一个图元。未来我们会引入WebGL进行2D渲染。
力导布局的优化需要算法做优化，同时也建议在业务测做优化，比如缓存第一次力导后的结果，再通过preset布局预设。

**Comment by tianqingfish** [comment]
> @iventong Graphin2.0做了一些性能优化，200节点200边现在应该不会卡了。但是超过500节点的力导还是会卡，超过1000节点的渲染，依旧会卡。这个问题我们在想办法解决，交互优化是一种方式，参考：https://graphin.antv.vision/graphin/behaviors/behaviors 在拖拽和缩放的时候仅展示keyshape，即显示一个图元。未来我们会引入WebGL进行2D渲染。 力导布局的优化需要算法做优化，同时也建议在业务测做优化，比如缓存第一次力导后的结果，再通过preset布局预设。

现在带上边的label的graphin-force布局，大约200节点。在不关闭动画的情况下还是会卡，关闭动画感觉会有长的js执行任务，阻塞渲染。
