### ISSUE TITLE
多边条件下，关于线的定义和label的定义

### ISSUE THREAD

**Issue by yangjiao2** [antvis/Graphin#157]
**Describe the solution you'd like**
想要在多边的情况下，可以定义边和label

现阶段我知道可以定义autopoly之后，
    style: {
        lineWidth: 22, // 单边的定义
        line: {
            width: 22, //多边的定义
        },
    },
我希望可以有多边的顶一下，以下内容可以改变
shape 我希望也是像line 一样
1）无箭头
2）可改变颜色
3）labelconfig可以自定义

**Describe alternatives you've considered**
如果用register edge, 可以麻烦在官方文档或者这里给一个例子嘛？

谢谢

**Comment by pomelo-nwu** [comment]
@yangjiao2 很抱歉这么晚回复你，1.x因为架构问题，这块的功能需求一直没有解决。新版本graphin2.x 架构调整后，在边的设计上满足了你最初提的问题，支持对边的情况下，对箭头，颜色，label均可调整：https://antv.vision/graphin-docs/graphin/render/edge

**Comment by yangjiao2** [comment]
太棒啦
happy Chinese new year :)

**Comment by yangjiao2** [comment]
通过砍需求，强制双边，叠加标签，小业务已经上线半年了 hhhhhh
                const containsPloy = false;
                let defaultEntry: PolyEdgeProps = {
                    source: headEntityType,
                    target: tailEntityType,
                    label: relationType,
                    edgeCategory: containsPloy ? MULTI_DIRECTION_REVERSE : SINGLE_DIRECTION,
                };
                // 情况1： 自环
                if (headEntityType === tailEntityType) {
                    defaultEntry = {
                        ...defaultEntry,
                        edgeCategory: LOOP,
                    };
                } else if (edgeMap.hasOwnProperty(tailEntityType)) {
                    // 情况2: 双边
                    const edgesProps: PolyEdgeProps[] = edgeMap[tailEntityType];
                    const polyedgeIndex = edgesProps.findIndex((edge: PolyEdgeProps) => edge.target === headEntityType);
                    if (polyedgeIndex != -1) {
                        defaultEntry = {
                            ...defaultEntry,
                            edgeCategory: MULTI_DIRECTION_REVERSE,
                        };
                        const edge: PolyEdgeProps = edgesProps[polyedgeIndex];
                        edgesProps[polyedgeIndex] = {
                            ...edge,
                            edgeCategory: MULTI_DIRECTION,
                        };
                        edgeMap[tailEntityType] = edgesProps;
                    }
                }

                // 情况3: 标签叠加
                if (edgeMap.hasOwnProperty(headEntityType)) {
                    const edgesProps: PolyEdgeProps[] = edgeMap[headEntityType];
                    const existedEdgeIndex = edgesProps.findIndex(
                        (edge: PolyEdgeProps) => edge.target === tailEntityType,
                    );
                    if (existedEdgeIndex != -1) {
                        const edge: PolyEdgeProps = edgesProps[existedEdgeIndex];
                        edgesProps[existedEdgeIndex] = {
                            ...defaultEntry,
                            // label叠加
                            label: edge.label + labelSeperator + relationType,
                        };
                    } else {
                        edgesProps.push(defaultEntry);
                    }
                    edgeMap[headEntityType] = edgesProps;
                } else {
                    edgeMap[headEntityType] = [defaultEntry];
                }
