### ISSUE TITLE
graphin-components 在 TS 项目中无法使用

### ISSUE THREAD

**Issue by deart1mer** [antvis/Graphin#16]
**Describe the bug**

使用 TS 的时候发现没有 types，看了一下 package.json 是指定了的，但是 types 在 `./dist/src/index.d` ，`src` 被 .npmignore 忽略掉了。

https://github.com/antvis/Graphin/blob/2189c43e2239ff93cd30329e0d325182a0b9e648/packages/graphin-components/package.json#L6

https://github.com/antvis/Graphin/blob/ee20aba4140084fa6323f5ff3aee5213166ac2af/packages/graphin-components/.npmignore#L50

**To Reproduce**

// Add Code Sanbox reproduce link using this template: https://codesandbox.io/s/data-driven-3o71b

**Expected behavior**

TS 项目能正常引入组件。

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pomelo-nwu** [comment]
是的，是有这个问题，我们稍后重新打包下。感谢你的反馈

**Comment by deart1mer** [comment]
已经解决了，感谢。
