### ISSUE TITLE
BUG：Toolbar中全屏后，原有高度出现问题

### ISSUE THREAD

**Issue by pomelo-nwu** [antvis/Graphin#167]

**Comment by dengl11** [comment]
+1

**Comment by pomelo-nwu** [comment]
2.0中 Toolbar重新设计，预计在2.0.1版本上线

**Comment by diklios5768** [comment]
> 2.0中 Toolbar重新设计，预计在2.1.0 版本上线

请问现在2.0.5版本全屏和保存图片等功能是不能使用了吗

**Comment by pomelo-nwu** [comment]
@dengl11 https://insight.antv.antgroup.com/#/open/assets-list?assetKey=LayoutSwitch 组件层不再透出toolbar
