### ISSUE TITLE
如何点击某个节点高亮所有关联的节点？

### ISSUE THREAD

**Issue by stalary** [antvis/Graphin#174]
如何点击某个节点高亮所有关联的节点，目前默认只能高亮关联的一级

**Comment by pomelo-nwu** [comment]
@stalary 目前这个特殊逻辑，graphin没有内置，这里有一个方法可以参考：[可以在options中关闭highlight](https://graphin.antv.vision/zh/docs/api/graphin#options)
)，然后自己实现一个highlight逻辑：找到你要高亮的多级节点，设置他们的高亮样式。
后续也欢迎你把这段逻辑PR过来，贡献到graphin-site的demo中。

**Comment by Christian-Nja** [comment]
@pomelo-nwu  can this be used also for multiple node selection?
