### ISSUE TITLE
Adding G6 timebar to Graphin in React

### ISSUE THREAD

**Issue by Wathsara** [antvis/Graphin#176]
Is there any possibility of adding the [G6 Time bar]( https://g6.antv.vision/en/examples/tool/timebar#simple-timebar) to the Graphin graph in a React Application? 
![image](https://user-images.githubusercontent.com/31571237/96351504-5bdba100-10d9-11eb-8acb-6813bfc4292d.png)

**Comment by ecloudz2020** [comment]
@Wathsara I see this issue closed, wondering how you resolved it, do you have any example of how you achieved this.

**Comment by pomelo-nwu** [comment]
@ecloudz2020 If you want to use the Timebar provided by G6, you can refer to the implementation of MiniMap：https://github.com/antvis/Graphin/blob/master/packages/graphin-components/src/MiniMap/index.tsx

**Comment by scarletfrank** [comment]
> @ecloudz2020 If you want to use the Timebar provided by G6, you can refer to the implementation of MiniMap：https://github.com/antvis/Graphin/blob/master/packages/graphin-components/src/MiniMap/index.tsx

现在想要在Graphin里加入G6时间轴，还是要靠这样的实现方式吗。
