### ISSUE TITLE
Multiple node selection

### ISSUE THREAD

**Issue by Christian-Nja** [antvis/Graphin#179]
**Is your feature request related to a problem? Please describe.**
How to select multiple nodes? Currently, when i click on a second node the previously selected goes unselected

**Describe the solution you'd like**
I would like to select multiple nodes and operate on a list of them, seeing the highliting, and to unselect them clicking again on it.

**Context**
I tried passing G6 options without success:

```
        <Graphin
            data={graph.toJson()}
            layout={{ name: "dagre", options: {} }}
            ref={graphRef}
            options={{
                modes: {
                    default: [
                        {
                            type: "click-select",
                            trigger: "ctrl",
                            multiple: "true",
                        },
                    ],
                },
            }}
        >
```

**Comment by sroertgen** [comment]
for me multi-selection works with holding `alt`-key (I'm on a Mac)
