### ISSUE TITLE
请问如何在本地运行起来这个项目呢

### ISSUE THREAD

**Issue by RuojiWang** [antvis/Graphin#185]
我在windows上面安装了node.js和npm，然后安装graphin：npm install @antv/graphin-components --save，然后下载了https://codesandbox.io/s/data-driven-fkue0 中的例子，在控制台中cd到例子src所在的路径，然后node index.js，报错显示SyntaxError: Cannot use import statement outside a module，我通过指令安装react：npm install --save react react-dom，错误依然没有解决，此外还Google了很多解决方案都没能运行起这个Demo。

另外README.md中的钉钉交流群也已经过期了，希望有一个新的平台或者交流媒介实现相关的交流吧。

感谢！

**Comment by pomelo-nwu** [comment]
查看readme里的开发指引，依赖是lerna自动安装的：https://github.com/antvis/Graphin/blob/master/README.zh-CN.md#%E5%BC%80%E5%8F%91-graphin 。
群二维码：
![image](https://user-images.githubusercontent.com/10703060/102183881-884d4700-3ee9-11eb-904b-acd347f5e766.png)
