### ISSUE TITLE
Does Graphin support TreeGraph in G6?

### ISSUE THREAD

**Issue by laubonghaudoi** [antvis/Graphin#188]
I read through the Graphin documents and tutorials, it seems that all examples are made in general graphs. Is it possible to pass a tree structure like this:
```javascript
data = {
  id: "id1",
  children: [
    {
      id: "id2",
      children: []
    }
  ]
}
```
into the `<Graphin data={data}>` component? How to make Graphin draw a tree structure like [these examples](https://g6.antv.vision/en/examples/gallery#category-CompactBox)?

**Comment by pomelo-nwu** [comment]
@laubonghaudoi  The current version of graphin1.x does not support G6 TreeGraph. You can try using [hierarchy](https://github.com/antvis/hierarchy ) first layout data, and then through transtree2graph (this function has to be written by yourself) to convert the tree structure into the graph structure, and load it into graphin to render.
Of course, according to the user's development feedback, we have already supported tree graph in version 2.0（you can see [this demo](https://github.com/antvis/Graphin/blob/graphin-2.0/packages/graphin/docs/render/data/CompactBox.tsx)）, but version 2.0 will be released in mid January next year

**Comment by laubonghaudoi** [comment]
Thank you! Looking forward to the January release next year. Kudos to you guys amazing work!
