### ISSUE TITLE
 国内镜像graphin 的产品首页 页面 404

### ISSUE THREAD

**Issue by zxhycxq** [antvis/Graphin#194]
**Describe the bug**
https://antv.gitee.io/zh/about 页面下，点击graphin 的“产品首页”到 https://antv-graphin.gitee.io/zh 是 404

**To Reproduce**

无

**Expected behavior**
 404

**Desktop (please complete the following information):**
  mac Chrome 浏览器

**Additional context**
无

**Comment by pomelo-nwu** [comment]
感谢你的反馈。我这边按照你的提示路径 点击了测试发现是好的，是不是网络问题或者浏览器缓存呢？可以清理下浏览器缓存，再试试？

**Comment by zxhycxq** [comment]
> 感谢你的反馈。我这边按照你的提示路径 点击了测试发现是好的，是不是网络问题或者浏览器缓存呢？可以清理下浏览器缓存，再试试？

刚才看了下可以，可能确实有缓存吧，之前点击两次都是 404.没事就好。谢谢了
