### ISSUE TITLE
how to change legend node label's color?切换为深色主题后，图例文本设置白色不起作用

### ISSUE THREAD

**Issue by zhangpp2019** [antvis/Graphin#199]
**Describe the bug**

**To Reproduce**

// Add Code Sanbox reproduce link using this template: https://codesandbox.io/s/data-driven-3o71b

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhangpp2019** [comment]
请问：graphin.theme='dark'，设置深色主题后，graphin-component组件中Legend图例文本颜色、如何设置为白色（浅色系）？我尝试覆盖样式 ul.graphin-components-legend-content li.item > .label {
      color:#fff;
    }，但未生效。

**Comment by pomelo-nwu** [comment]
@zhangpp2019 ,第一个问题“设置深色主题后，graphin-component组件中Legend图例文本颜色是浅色”，这是因为，对于<Legend.Node />组件没有做theme的处理，这个等下我发包解决下。
问题二“尝试覆盖样式 未生效”是因为style 内联样式优先级比CSS类 高

**Comment by pomelo-nwu** [comment]
![image](https://user-images.githubusercontent.com/10703060/105807443-f9037b00-5fe0-11eb-881b-0c9f548fef5c.png)
刚刚发布 [graphin-components@2.0.0-beta.7(https://www.npmjs.com/package/@antv/graphin-components/v/2.0.0-beta.7) 解决了这个问题
