### ISSUE TITLE
和g6版本同步更新

### ISSUE THREAD

**Issue by cmdares** [antvis/Graphin#20]
如题，g6引擎更新了很多内容，希望平台能够定期和g6最新引擎保持一致性。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zxc0328** [comment]
这次是因为 G6 新版有一个问题影响了 Graphin，现在已经修复了。Graphin 本周末会发新版本的。后面也会跟进 G6 的版本。

**Comment by cmdares** [comment]
:)
