### ISSUE TITLE
Set node position to top of the canvas

### ISSUE THREAD

**Issue by ajainvivek** [antvis/Graphin#207]
**Describe the bug**

The default node position is set to the middle of the canvas for tree layout for the item focused

![image](https://user-images.githubusercontent.com/1182600/106683571-d8f33d80-6618-11eb-9a48-9982aac4f7a5.png)

How do we define the position to be top for the focus item node. The desired output should look like below screenshot

![image](https://user-images.githubusercontent.com/1182600/106683697-19eb5200-6619-11eb-8cad-8ddcfef77385.png)

**To Reproduce**

https://codesandbox.io/s/dry-fog-3qtrs?file=/index.html

**Expected behavior**

Set position to be top of the layout for the focus item node. So we don't end up having empty spaces. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 87.0

**Comment by pomelo-nwu** [comment]
@ajainvivek `graph.focusItem` places the focused node at the center of the canvas by default. If you need to place the Root node at the top, you can try adding `graph.translate(0,canvasHeight/2)` to pan the canvas again
![image](https://user-images.githubusercontent.com/10703060/106839312-ebcd4700-66d8-11eb-8892-bd7a7ce354f2.png)

**Comment by ajainvivek** [comment]
@pomelo-nwu sweet. Thanks for the suggestion. 👍
