### ISSUE TITLE
Hidden Label of Node Appears after Hovering

### ISSUE THREAD

**Issue by dnlfrst** [antvis/Graphin#208]
**Describe the bug**
Using the following configuration to hide a node:

```React
defaultNode={{
  style: {
    label: {
      visible: false
    }
  }
}}
```

only works until the user hovers over a node. At that point, the label of the said node appears again and stays visible.

**To Reproduce**

To reproduce the issue, take a look at [this MWE](https://codesandbox.io/s/hidden-label-appears-after-hovering-oergx).

**Expected behavior**

With the above configuration applied, I would expect the node label to stay hidden regardless of the user's interaction with the graph.

**Environment:**
 - OS: macOS Big Sur
 - Browser: Google Chrome 88.0.4324.96

This issue surfaced in version **2.0.0-beta.8** and is present throughout version **2.0.0-beta.11**.

**Comment by pomelo-nwu** [comment]
@dnlfrst Thanks for the problem you pointed out, I have fixed it,[ please check:](https://github.com/antvis/Graphin/blob/master/packages/graphin/src/shape/graphin-circle.ts#L120) ，I will release 2.0.0-beta.12 later to solve this issue
But in usage. When hovering, the style of the node is determined according to the data in the status. If label.visible is not defined, it will be parsed as true by default. Therefore, you still need to add a line of code here, [see](https://github.com/antvis/Graphin/blob/master/packages/graphin/docs/render/element/demos/node-default.tsx#L35)。

**Comment by dnlfrst** [comment]
Thanks for tackling this issue so quickly, the labels are now hidden as expected!
