### ISSUE TITLE
希望支持节点文本超长自动隐藏或者省略号表示

### ISSUE THREAD

**Issue by JasonZhang1991** [antvis/Graphin#209]

**Comment by JasonZhang1991** [comment]
最好在text上扩充css overFlow配置项

**Comment by pomelo-nwu** [comment]
@JasonZhang1991 好的，感谢提出问题。Graphin 计划在 label 字段中新增 maxWidth 用来自动控制 label 的长度，超过隐藏，也将支持文本中 \换行。这将在正式版本中支持。
现在可以先在业务层做，用一个JS函数去判断字体长度，多余长度隐藏，然后把解析后的label传给graphin的 style.label.value 。 当然如果你需要更高级的功能，比如hover上去，隐藏的节点再次出现，可以将数据中存放完整的label数值，hover上去的时候，update当前的label即可。

**Comment by yizhengfeng-jj** [comment]
> @JasonZhang1991 好的，感谢提出问题。Graphin 计划在 label 字段中新增 maxWidth 用来自动控制 label 的长度，超过隐藏，也将支持文本中 \换行。这将在正式版本中支持。
> 现在可以先在业务层做，用一个JS函数去判断字体长度，多余长度隐藏，然后把解析后的label传给graphin的 style.label.value 。 当然如果你需要更高级的功能，比如hover上去，隐藏的节点再次出现，可以将数据中存放完整的label数值，hover上去的时候，update当前的label即可。

请问这个功能上线了吗？按照你的做法，设置position不能正常居中
