### ISSUE TITLE
ctrl+左键进行多选节点

### ISSUE THREAD

**Issue by cmdares** [antvis/Graphin#21]
如题，目前平台没有多选功能，期望能够增加节点多选。比如在多选操作之后，进行统一拖拽，统一扩展节点，统一合并到一个组等等的多节点操作。期望能够优先增强这些基础能力。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pomelo-nwu** [comment]
这个是迭代计划的一部分

**Comment by baizn** [comment]
@pomelo-nwu  G6 内置的多选 https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#click-select

**Comment by ulisescarreonalvarez** [comment]
Hi @baizn i added the script like:

```
const register =  {
  behavior: () => [{
    modes: {
      default: [
        {
          type: 'click-select',
          trigger: 'ctrl',
        },
      ],
    },
  }],
};
```

`<Graphin data={graphReducerData} layout={options}   register={register}>`

But i get the error:

```
TypeError: item.register is not a function
index.js:4554
TypeError: this.clearEvents is not a function
2 index.js:6909
TypeError: item.register is not a function

Any advice?
```
