### ISSUE TITLE
😁  解决方案交流 

### ISSUE THREAD

**Issue by pomelo-nwu** [antvis/Graphin#211]

**Comment by jizhi77** [comment]
<img width="947" alt="20617470-319D-4F80-B6EE-CAAE5BC5668A" src="https://user-images.githubusercontent.com/30496928/127800409-7126abd6-dd70-4a1d-a4a1-751ea2d2887a.png">

如上，类似这样的场景在 G6 里实现大概应该是什么思路？

**Comment by pomelo-nwu** [comment]
@jizhi77 G6可以实现，参考：https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo 但是，我们更推荐这种图使用X6处理：https://x6.antv.vision/zh/examples/node/group#collapsable
