### ISSUE TITLE
基础功能建议

### ISSUE THREAD

**Issue by cmdares** [antvis/Graphin#22]
针对选中节点需要提供如下操作：
1、隐藏节点、显示隐藏的节点、删除节点，恢复隐藏；删除和隐藏节点后，将图形界面上的和选中节点的边也隐藏或删除。
2、可以针对选中的节点（可能是多个）设置：大小，高亮，填充、颜色，标签（可多值）、轮廓、背景图片等主要控制显示的属性。
3、针对选中节点可以合并成一个Group，并对Group名称，类型、样式等参数提供编辑、如：将N个对象合并成一个群体。合并之后，节点隐藏，组节点显示。
4、针对Group类型的节点，支持“展开”操作，节点的组合和展开可以执行多次，即节点之间、节点与组，组之间可以反复组合和展开。
组合后，组外其他关联组内节点的边需要和组发生链接。（需要平衡边的显示方式）

选中边：
1、可设置边的颜色、线条、方向（最好能够无向图和有向图的混合显示，即画布上一部分节点之间是无向关联的，一部分是有向关联）、边粗细(体现关系密切程度，可考虑权重)、边的Label(针对复杂多类型关系网络关系类型很重要)。
2、边需要提供事件响应，比如：点击或双击边之后，右侧显示关系构成的情况，时间，内容等。

暂时先梳理了一些最为基础的功能要求。希望官方能够仔细参考，完善。

**Comment by pomelo-nwu** [comment]
Graphin在交互这块确实还欠缺很多能力，我们底层依赖G6，需要和G6一起成长和完善，这需要个过程

**Comment by baizn** [comment]
@pomelo-nwu  隐藏显示节点这个里面已经做了， G6是支持的，需要在 Graphin 层处理下，https://g6.antv.vision/zh/docs/manual/cases/relations

**Comment by RuojiWang** [comment]
前端小白弱弱问一哈，这个demo是如何运行起来的呢

**Comment by pomelo-nwu** [comment]
@RuojiWang https://github.com/antvis/Graphin/blob/master/README.zh-CN.md#%E5%BC%80%E5%8F%91-graphin
