### ISSUE TITLE
Attempted import error: 'IInteractorService' is not exported from './services/interactor/IIteractorService'.

### ISSUE THREAD

**Issue by Christian-Nja** [antvis/Graphin#224]
**Describe the bug**
Import error from a dependent component

```
../odp-reactor/node_modules/@antv/g-webgpu-core/es/index.js 130:0-132:659
Attempted import error: 'IInteractorService' is not exported from './services/interactor/IIteractorService'.
```

a link to related issue: 

https://github.com/antvis/G6/issues/2465#issue-774684433

**To Reproduce**
create new react app
`npx create-react-app myApp`
install graphin 
```
npm install @antv/graphin@latest --save
...
```
import `Graphin` component

// Add Code Sanbox reproduce link using this template: https://codesandbox.io/s/data-driven-3o71b

**Expected behavior**
It should not breaks

**Comment by pomelo-nwu** [comment]
@Christian-Nja Well, this problem has been solved in version 2.0, check your codesandbox, everything is ok
![image](https://user-images.githubusercontent.com/10703060/109442167-61c39480-7a72-11eb-92b2-c091ba0d92dc.png)
