### ISSUE TITLE
Node touch on mobile devices

### ISSUE THREAD

**Issue by Christian-Nja** [antvis/Graphin#227]
**Is your feature request related to a problem? Please describe.**
Is is possible to register node touch event on mobile devices?
Actually it's only possible to drag the canvas

**Describe the solution you'd like**
Possibility to register behaviour on node touch event. Such for node:click.

**Comment by pomelo-nwu** [comment]
@Christian-Nja Need support for mobile events from the underlying `@antv/g`, you can check https://github.com/antvis/G6/tree/master/packages/mobile. If g6-mobile is completed, I will notify you as soon as possible

**Comment by Christian-Nja** [comment]
@pomelo-nwu great thank you for the fast reply!
