### ISSUE TITLE
希望支持功能:力导时是否允许拖拽后其他节点重新进入力导流程

### ISSUE THREAD

**Issue by hanxinran** [antvis/Graphin#228]
1.0版本的autoFollowWithForce这个功能,希望2.0也支持

**Comment by pomelo-nwu** [comment]
@hanxinran 力导节点拖拽后重新restart，可以参考1.x的做法在业务端先实现：https://github.com/antvis/Graphin/blob/v1.6.4-graphin/packages/graphin/src/events/drag-with-force.ts ，我们也会尽快在2.x的版本中内置该Behaviors，感谢指出

**Comment by pomelo-nwu** [comment]
@hanxinran 详见PR：https://github.com/antvis/Graphin/pull/229/commits/89f7696dbe9b6623ff15093d7208bbd377ea0ab3 ，文档在：https://graphin.antv.vision/graphin/behaviors/node/
