### ISSUE TITLE
📝 图可视分析 参考案例

### ISSUE THREAD

**Issue by cmdares** [antvis/Graphin#23]
https://help.aliyun.com/video_detail/63227.html?spm=a2c4g.11186623.4.5.7b57af833Sm9xs
https://grapheco.github.io/InteractiveGraph/dist/examples/example1.html
国内一些不错的案例产品，可以参考一些功能和操作形态！
本热使用过一些开源的软件，cytoscape （客户端版本）针对图的操作还是不错的，和gephi各有千秋
而针对品质来讲cytoscape更胜一筹，但是cytoscape有点太专业，尤其是左侧的针对图的操作见仁见智。
综上，I+平台的针对国内可视化网络分析的使用习惯，还是有很多借鉴的意义的。

**Comment by pomelo-nwu** [comment]
我们和I+的核心开发者之前做过很多次交流，他们在关系可视分析领域做的很不错，从底层渲染到上层产品设计都有自己的一套体系，graphin确实有很长的路要走。感谢你提的建议。graphin其实也有参考的竞品：ReGraph，这是我们当时的调研报告：https://zhuanlan.zhihu.com/p/87956723
