### ISSUE TITLE
TS类型定义错误: defaultNode/defaultEdge/defaultCombo 

### ISSUE THREAD

**Issue by Anonymity94** [antvis/Graphin#230]
**Describe the bug**
defaultNode/defaultEdge/defaultCombo TS类型定义错误

现状：
[graphin/src/typings/type.ts#L108-L112](https://github.com/antvis/Graphin/blob/master/packages/graphin/src/typings/type.ts#L108-L112)

```tsx
  /** 默认的节点样式 */
  defaultNode?: Partial<NodeStyle>;
  /** 默认的边样式 */
  defaultEdge?: Partial<EdgeStyle>;
  /** 默认的Combo样式 */
  defaultCombo?: Partial<ComboStyle>;
```

按照 [`G6` 的配置](https://github.com/antvis/G6/blob/master/packages/core/src/types/index.ts#L259-L284
) ，看了下 `Graphin` 示例代码，上述定义应该是不对的。和样式相关的缺少一层 `style` 包裹。
下面的代码并不会正确的应用用户配置的默认样式。

[graphin/src/Graphin.tsx#L216-L218](https://github.com/antvis/Graphin/blob/master/packages/graphin/src/Graphin.tsx#L216-L218)

```tsx
defaultNode: isGraphinNodeType ? deepMix({}, defaultNodeStyle, defaultNode) : defaultNode,
defaultEdge: isGraphinEdgeType ? deepMix({}, defaultEdgeStyle, defaultEdge) : defaultEdge,
defaultCombo: deepMix({}, defaultComboStyle, defaultCombo), // TODO:COMBO的样式需要内部自定义
```

---

看了下源码，粗暴的修复了一下，并不全面。
不合适的话，你们这个地方好好改一下吧。

```
  /** 默认的节点样式 */
  defaultNode?: Partial<{
    type?: string;
    style: NodeStyle;
    [key: string]: any;
  }>;
  /** 默认的边样式 */
  defaultEdge?: Partial<{
    type?: 'graphin-line';
    style: EdgeStyle;
    [key: string]: any;
  }>;
  /** 默认的Combo样式 */
  defaultCombo?: Partial<{
    type?: string;
    style: ComboStyle;
    [key: string]: any;
  }>;
```

**To Reproduce**

// Add Code Sanbox reproduce link using this template: https://codesandbox.io/s/data-driven-3o71b

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pomelo-nwu** [comment]
@Anonymity94 感谢你的PR，可以加我钉钉号更进一步交流：kw2ku3f
