### ISSUE TITLE
集成 Antd 的 Popover 组件后，节点无法拖拽/点击选中

### ISSUE THREAD

**Issue by zhangxiaoshang** [antvis/Graphin#232]
**Describe the bug**
集成 Antd 的 Popover 组件后，节点无法拖拽。
复现案例可以直接查看官网Demo: [开放组件：集成 Antd 的 Popover 组件](https://graphin.antv.vision/components/interaction/tooltip#%E5%BC%80%E6%94%BE%E7%BB%84%E4%BB%B6%EF%BC%9A%E9%9B%86%E6%88%90-antd-%E7%9A%84-popover-%E7%BB%84%E4%BB%B6)

**Expected behavior**
节点可以拖拽

**Comment by pomelo-nwu** [comment]
@zhangxiaoshang 我尝试用pointer-events来解决Popover需要的DOM遮挡节点问题，但是还是存在一些问题，因为，在下一个版本，官方会实现一个类Antd的Popover组件，如果你的业务急需要，也可以在业务端先自行实现。

**Comment by pomelo-nwu** [comment]
@zhangxiaoshang 更新graphin和components到2.0.5版本，查看：https://graphin.antv.vision/components/interaction/tooltip
