### ISSUE TITLE
节点类型声明

### ISSUE THREAD

**Issue by GrayFrost** [antvis/Graphin#24]
``` typescript
export interface Node {
    /** 节点源数据 */
    data: {
        /** 唯一标示ID，必选 */
        id: string;
        /** 节点数据类型 */
        type?: string;
        /** 节点文本 */
        label?: string;
        /** 节点属性 */
        properties?: any[]; // eslint-disable-line
    };
    /** 唯一标示ID，必选 */
    id: string;
    /** 节点类型 */
    shape?: string;
    /** 节点样式 */
    style?: Partial<NodeStyle>;
    /** 节点位置信息 */
    x?: number;
    y?: number;
    /** 内置的布局，追加的额外属性 */
    layout?: NodeLayoutType;
    /** 节点度数 */
    degree?: number;
    searchTypes?: string[];
}
```
想问一下，节点类型用string声明似乎不太方便，之后会调整吗？

**Comment by pomelo-nwu** [comment]
不方便的点是什么，可以举例说明下吗

**Comment by GrayFrost** [comment]
> 不方便的点是什么，可以举例说明下吗

因为我看[Graphin文档](https://antv-graphin.gitee.io/zh/docs/api/graphin)和[G6文档](https://www.yuque.com/antv/g6/internal-node)，不清楚`NodeShape`到底有哪些值。
就是希望`NodeShape`里内置的类型可以用enum枚举出来，或者在注释里备注一下。

**Comment by pomelo-nwu** [comment]
好的，目前只内置了CircleNode 这一个NodeShape，它的定义与描述在：https://github.com/antvis/Graphin/blob/master/packages/graphin/src/shape/render/CircleNode.ts 本周会把相关的组件演示补齐

**Comment by zxc0328** [comment]
NodeShape 内的值包括 G6 的内置节点和自定义节点，枚举不太现实。后面文档中会解释清楚。
