### ISSUE TITLE
missing script: bootstrap

### ISSUE THREAD

**Issue by afuyo** [antvis/Graphin#243]
**Describe the bug**
npm run bootstrap returns error: missing script: bootstrap

**To Reproduce**
I follow the readme in order to run  graphin studio.  Shouldn't it be defined in package.json? 

npm run bootstrap

**Comment by pomelo-nwu** [comment]
@afuyo https://github.com/antvis/Graphin/blob/master/package.json#L14

**Comment by afuyo** [comment]
Thanks, it was very helpful. Still getting some errors when running npm run studio: 
`
Error: Cannot find module 'C:\github\Graphin\packages\graphin-studio\node_modules\webpack-dev-server\bin\webpack-dev-server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []`

**Comment by pomelo-nwu** [comment]
@afuyo studio is still being refactored, please run `npm run docs` to view the dumi docs

**Comment by mamonaabdullah122** [comment]
Same issue here any solution for that.

**Comment by jnkstr** [comment]
Same, still no solution?

**Comment by pomelo-nwu** [comment]
> Same, still no solution?

npm run bootstrap:ci 

or

npx lerna bootstrap
