### ISSUE TITLE
MiniMap 组件离开当前页面之后报错

### ISSUE THREAD

**Issue by ZangYuSong** [antvis/Graphin#259]
Graphin 版本：2.0.7

错误信息：
![image](https://user-images.githubusercontent.com/8529359/122324687-cc360d00-cf5b-11eb-92e7-a2c98180c88b.png)

解决：
![image](https://user-images.githubusercontent.com/8529359/122323648-00103300-cf5a-11eb-9b8c-8e47d978f2e4.png)

请求：
不知道我这样写的对不对，麻烦这边解决一下这个问题。

**Comment by pomelo-nwu** [comment]
@ZangYuSong 好的，感谢上报问题，晚些时候我们处理下
