### ISSUE TITLE
从其他布局切换到graphin-force后DragNodeWithForce效果失效

### ISSUE THREAD

**Issue by sdj0001** [antvis/Graphin#263]
看了源码，发现切换布局以后，Graphin组件没有同步更新GraphinContext里面的layout的值，导致DragNodeWithForce从GraphinContext里面拿到的layout对象还是切换布局之前的值，导致DragNodeWithForce效果失效

**Comment by xiaohe2510** [comment]
这个问题有法解决吗，我也遇到了，而且要求必须解决

**Comment by sdj0001** [comment]
> 而且

**Comment by sdj0001** [comment]
> 看了源码，发现切换布局以后，Graphin组件没有同步更新GraphinContext里面的layout的值，导致DragNodeWithForce从GraphinContext里面拿到的layout对象还是切换布局之前的值，导致DragNodeWithForce效果失效

**Comment by sdj0001** [comment]
> 这个问题有法解决吗，我也遇到了，而且要求必须解决

只能改源代码了Graphin.js里面布局变化时更新context

**Comment by xiaohe2510** [comment]
> > 这个问题有法解决吗，我也遇到了，而且要求必须解决
> 
> 只能改源代码了Graphin.js里面布局变化时更新context

这个具体要如何更改呢，我这边对react和Graphin还不够太了解（小白一个），能具体说明一下吗

**Comment by pomelo-nwu** [comment]
@sdj0001 @xiaohe2510  晚些时候我看下这个问题

**Comment by xiaohe2510** [comment]
> @sdj0001 @xiaohe2510 晚些时候我看下这个问题
这个问题难弄吗，源码需要改哪个地方呢，我这边有时候失效，有时又是正常

**Comment by SamKiwi2021** [comment]
@xiaohe2510  @sdj0001  @pomelo-nwu 这个问题其实很好解决  Graphin组件在每次接收到新数据的时候会重置上下文。 你主需要在切换 布局的时候给 Graphin注入新数据就可以  即便没有数据更新 通过重设data  例如 `setData({...data})` 就可以触发重新渲染 然后DragNodeWithForce就正常了。

```jsx
const [mapData, setMapData] = useState(data);
  useEffect(() => {
    setMapData({ ...data });
}, [value]); // value 是布局的类型 

  return (
    <div style={{ width: '100vw', height: '100vh' }}>
      <Graphin
        data={mapData}
        layout={{
          type: value
        }}
    .......  无关的代码 ....... 
```
