### ISSUE TITLE
图标label拖动残影问题

### ISSUE THREAD

**Issue by lyyy-yb** [antvis/Graphin#267]
![image](https://user-images.githubusercontent.com/65581285/125579634-b3eadd95-703b-4ffd-88a9-753304eaac3e.png)
![image](https://user-images.githubusercontent.com/65581285/125579704-c4cc3e4e-3f34-496b-9b8b-6cee1f374ff1.png)
如同官网demo上这样，拖动边缘节点时候会有这种情况出现，附谷歌游览器版本号。

**Comment by pomelo-nwu** [comment]
@lyyy-yb 底层绘图引擎G，局部渲染导致的，两种解决办法：1.试着将节点的label的[fontFamily](树形结构)改为和浏览器字体一致的字体，2.关闭[局部渲染](https://github.com/antvis/Graphin/blob/master/packages/graphin/src/Graphin.tsx#L262) 默认情况下是打开的，需要Graphin层做一个Options配置，让用户可以手动关闭

**Comment by zhangzhongpu** [comment]
@pomelo-nwu 方法2：需要Graphin层做一个Options配置，不是很明白，可以更详细一点嘛

**Comment by zhangzhongpu** [comment]
@lyyy-yb 
![BBP JY1@~UH)I%L@G8$~FWW](https://user-images.githubusercontent.com/47777515/180644889-5958efce-89fb-4eaf-849e-655287f32e42.png)，也可以换行增加局部渲染的面积解决。
