### ISSUE TITLE
Support for @antv/g6-react-node?

### ISSUE THREAD

**Issue by genert** [antvis/Graphin#270]
**Describe the bug**
Trying to extend node component with JSX. 

The example provided by you works, however when I use the `@antv/g6-react-node` to create exactly the same node, it fails to render it correctly.

Assuming the library works with Graphin, all the nodes should look exactly the same, however node created with the library produces invalid node as the image shows:

<img width="627" alt="Screenshot 2021-07-26 at 15 03 32" src="https://user-images.githubusercontent.com/1218788/126985721-219717e7-32ca-428b-868b-3f5b6befadcb.png">

What is the issue causing this? Should't that library support Graphin as the latter is based on g6?

**To Reproduce**

Sandbox demonstration of the issue - https://codesandbox.io/s/show-case-of-custom-react-node-v2jzb

**Expected behavior**

All nodes should look the same.

**Comment by mxz96102** [comment]
Hi, I'm the writer of g6-react-node and jsx mode, In your example, you should assign color to it, and it seems your react node is with some error. There are several differents between the two, jsx mode will fallback to varname when meet null while react node just show nothing for it, this is my example https://codesandbox.io/s/show-case-of-custom-react-node-forked-qmrkp .

I'm glad to see you use them, and giving feed back.

**Comment by genert** [comment]
Hi @mxz96102, the null fallback, and styles fixed the issue.

Thank you!
