### ISSUE TITLE
Graphin主题切换问题

### ISSUE THREAD

**Issue by zhangjw-git** [antvis/Graphin#281]
根据官方说明：Graphin 目前还不能够对主题进行切换，即将 theme 设置为 React 的 state 状态，动态改变。预计在 2.1.0 版本加入。同时对于 GraphinComponents 内的组件，Theme 暂时也无法自动切换，预计在 2.2.0 版本加入.

目前尝试升级到2.3.0后发现还没有实现，请问大概在啥时候能支持呀，坐等。

**Comment by zhangjw-git** [comment]
该功能虽暂未实现，也可以讨巧一下，给同样需要该功能的同学一个调用思路，代码如下：  
  const changeTheme = () =>{
    /*
    Graphin 目前还不能够对主题进行切换，即将 theme 设置为 React 的 state 状态，动态改变。预计在 2.1.0 版本加入。
    同时对于 GraphinComponents 内的组件，Theme 暂时也无法自动切换，预计在 2.2.0 版本加入.
     */
    //暂时自己实现
    const { graph } = graphRef.current;
    let newTheme = 'dark'
    if (theme.mode == 'dark') {
      newTheme = 'light'
    }
    setTheme({mode: newTheme})
    localStorage.setItem('theme', newTheme)
    const dataBackup = graph.save()
    dataBackup.nodes.map((node)=>{
      //发现这种方案切主题后label可能不太正常，因此按需处理下
      node.style.label.fill = newTheme == 'light' ? 'black' : 'white'
    })
    //将graphin datasource置空，这边需要配合html里用datasource做下判断，成立时才渲染
    setDatasource(undefined)
    message.info('正在切换主题。。。')
    //这边需要等待500ms再设上datasource, 不然没效果
    setTimeout(() => {
      setDatasource(dataBackup)
      message.info(newTheme === 'light' ? '成功切换到浅色主题。' : '成功切换到深色主题。')
    }, 500);
  }

对应的html:  
      {  dataSource &&
            <Graphin data={dataSoure} layout={layout} ref={graphRef} theme={theme}></Graphin>
      }

结果就能正常动态切换主题啦。

**Comment by cliffordfajardo** [comment]
@zhangjw-git

您是否能够创建一个https://codesandbox.io/s/  或 http://stackblitz.com 您在上面共享的代码示例？

我想介绍这一点，可以稍后贡献一些东西

**Comment by pomelo-nwu** [comment]
@zhangjw-git 你可以参考 https://insight.antv.antgroup.com/#/open/assets-list?assetKey=ThemeSetting&tab=graph-components 的实现
