### ISSUE TITLE
Feature：Need to add a lock state to the node

### ISSUE THREAD

**Issue by pomelo-nwu** [antvis/Graphin#3]
Description: If the node is in the lock state, it will not participate in the layout. For example, in the force layout, the locked node will be fixed in place.

-- zh-CN -- 

功能描述：节点为lock状态，则不参与布局。比如在力导布局中，锁定的节点会固定在原处。

**Comment by baizn** [comment]
https://g6.antv.vision/zh/docs/api/nodeEdge/Node 
布局的时候可能需要加个开关，是否忽略 lock 状态的节点，另外缩放画布和拖动画布也需要加类似的处理，目前 G6 中只拖动节点处理了 lock 状态，接下来G6 层面的布局会加上对lock的处理。

**Comment by pomelo-nwu** [comment]
状态改造后完成
