### ISSUE TITLE
题  - 如何测试和查看新的`graphin`在开发期间的代码更改？ ----- Question: How to test & View new `graphin` code changes during development

### ISSUE THREAD

**Issue by cliffordfajardo** [antvis/Graphin#328]
你好Graphin团队，

我是该项目的新贡献者。

在我运行中运行graphin`命令后，在github代码中有一个位置，我可以渲染新的`graphin组件以验证我的代码在`graphin`文件夹工作中更改吗？

## English Translation
Hi Graphin team,
I am a new contributor of the project.

When i use `npm run graphin` to start to development in` Graphin`, what is your recommended method of testing the new change in the `graphin` code?

Is there a location in this GitHub code repository where I can load the `graphin` component, and verify that my` graphin` code is effective?

CC @pomelo-nwu

**Comment by cliffordfajardo** [comment]
Hi @Blakko, @niknbr
 I noticed you've recently contributed to the project. Do have any tips regarding the question above on how to contribute and test changes?

Thanks 🙏

**Comment by Blakko** [comment]
Hi @cliffordfajardo
I went down the quick and dirty road. I did set up a very simple npm demo app with graphin and implemented the functionalities in the node_modules files directly to quickly test the results. After that, I did the changes in the source code, compiled and swapped the node_modules files to give another round of tests. Finally, I opened the the PR

**Comment by timlrx** [comment]
On our side, we used vite and created a very simple demo to test the results.

**Comment by pomelo-nwu** [comment]
@cliffordfajardo You can read this [link](https://github.com/antvis/Graphin/blob/master/packages/graphin/docs/contributing.en-US.md) In the project root directory, execute `npm run docs` to see all the test demos 。

For example, you wrote a custom interactive component in the project, the source file is [here](https://github.com/antvis/Graphin/blob/master/packages/graphin/docs/register/behaviors/graphin-style.tsx)
The rendered demo is [here](https://graphin.antv.vision/en-US/graphin/register/behaviors)

![image](https://user-images.githubusercontent.com/10703060/146149646-556cd5c2-1bc5-4518-b895-b36fcde5d0bb.png)
