### ISSUE TITLE
源代码中增加g6子模块，便于开发中进行G6调试

### ISSUE THREAD

**Issue by semious** [antvis/Graphin#33]
开发过程中，有时会出现g6的异常信息，现在没有g6的源码，不便于进行问题排查，希望将源代码中增加g6子模块，便于开发中进行代码调试

**Comment by zxc0328** [comment]
Graphin 现在是打包出来的 es module，G6 是依赖你使用时候引入的那个，所以你只要在你的项目里面 link 一下本地的 g6 就行了。
