### ISSUE TITLE
Enable Github Discussions feature for Graphin Repository?

### ISSUE THREAD

**Issue by cliffordfajardo** [antvis/Graphin#336]
Hi Graphin team,

I was wondering if you would be open to enabling the Github Discussion's feature for the this repository.

Once the Github Discussion's tab is enabled, people can post their questions and that would help with finding questions and answers

- https://docs.github.com/en/discussions

Example of what Github Discussion's look like when enabled
- `react-query`'s github discussion's - https://github.com/tannerlinsley/react-query/discussions

**Comment by pomelo-nwu** [comment]
@cliffordfajardo  good idea: https://github.com/antvis/Graphin/discussions
