### ISSUE TITLE
更新graphin的data之后, 有没有页面渲染完成回调函数? 我想在回调函数里调整下页面缩放

### ISSUE THREAD

**Issue by kaykong** [antvis/Graphin#341]
### Describe the bug

`
setState({
  ..state,
  data: {
    nodes: [...oldNodes, ...newNodes],
    edge: [...oldEdges, ...newEdges]
  }
})
setTimeout(e => {
    graphRef.current.graph.fitView([20, 20])
}, 1000)
`

setState({
  ..state,
  data: {
    nodes: [...oldNodes, ...newNodes],
    edge: [...oldEdges, ...newEdges]
  }
})
setTimeout(e => {
    graphRef.current.graph.fitView([20, 20])
}, 1000)

目前是在setState之后, 设置一个定时器来更新fitView, 用起来不方便的, 想问下graphin有没有页面渲染完成回调函数? 我想在回调函数里调整下页面缩放

而且目前fitView 不支持动画, 用起来卡卡的, 不知道如何才能顺滑实现

### Your Example Website or App

test

### Steps to Reproduce the Bug or Issue

null

### Expected behavior

 null

### Platform

chrome

**Comment by lele1307** [comment]
可以自定义一个交互组件
通过 context 获取Graphin 中的 graph 实例
使用实例方法 graph.zoomTo()设置初始化的页面缩放
其中可增加animateCfg的相关配置 较为顺滑
