### ISSUE TITLE
升级2.4.10之后components里没有undoredo了

### ISSUE THREAD

**Issue by wangshangkun** [antvis/Graphin#347]
### Describe the bug

![image](https://user-images.githubusercontent.com/13530852/149478804-425b97ca-851a-4b25-ac21-509a4ba59477.png)

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

N/A

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kaykong** [comment]
哪个版本里有?

**Comment by wangshangkun** [comment]
> 哪个版本里有?

好像是没有的。 我看文档上给的有，纠结了一下午，暂且先不用这个功能吧

**Comment by TingOOOgniT** [comment]
https://antv-graphin.gitee.io/components/interaction/undo-redo
这也太假了吧。。

**Comment by nylqd** [comment]
以前1.x有，后来2.x之后应该是还没有实现，可以参考1.x的时候搞一把

**Comment by pomelo-nwu** [comment]
https://github.com/antvis/G6VP/blob/master/packages/gi-assets-advance/src/components/hooks/useRedoUndo.tsx 可以参考这个实现
