### ISSUE TITLE
有类似G6的内置交互行为吗，例如tooltip这种？

### ISSUE THREAD

**Issue by hubl95** [antvis/Graphin#35]

**Comment by pomelo-nwu** [comment]
内置了画布平移动，缩放，节点拖拽，节点和边高亮 4种交互行为：详见Options配置文档：https://graphin.antv.vision/zh/docs/api/graphin#options。源码详见https://github.com/antvis/Graphin/blob/master/packages/graphin/src/controller/init.ts#L67
至于Tooltip这种，我们是将交互绑定在组件层面，可以参考ContextMenu右键菜单的实现：https://github.com/antvis/Graphin/blob/master/packages/graphin-components/src/components/context-menu/useContextmenu.ts

**Comment by hastings0714** [comment]
```
<Graphin
  options={{
    modes: {
      default: [
        // ...
        {
          type: 'tooltip', // 提示框
          formatText(model) {
            const { label, id } = model;
            // 提示框文本内容
            const text = `${label}<br/> ${id}`;
            return text;
          },
        },
      ],
    },
  }}
/>
```
可以这样把g6 的 tooltip 加进来  亲测有效。
