### ISSUE TITLE
GraphinStudio import error

### ISSUE THREAD

**Issue by necatiCelik** [antvis/Graphin#353]
### Describe the bug

Hi, 
We get an error when we try to run "graphin" and import it to our project. Do you have any idea why this is? Thank you for your help. 

Attached are some of the errors I got.

#![Ekran Alıntısı1](https://user-images.githubusercontent.com/26160975/152520021-9b55304d-415c-49a8-9a3d-f72e79bdeb04.JPG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/26160975/152520024-86a41959-74e1-4cef-8d3a-cc598aebb8c0.JPG)

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

We only import graphin-studio files to my project but it give error for "@com", "@antv/graphin/dist/types" vb.

### Expected behavior

We will waiting for run to graphin-studio

### Platform

- OS: Windows
- Browser: Chrome
- Version: 97.0.4692.99

**Comment by pomelo-nwu** [comment]
@necatiCelik GraphinStudio 在2.x版本不维护了，我们换到新的项目来完成这些内容：https://github.com/antvis/G6VP
