### ISSUE TITLE
无法更新视图，报 Uncaught TypeError: Cannot assign to read only property 'style' of object '#<Object>'

### ISSUE THREAD

**Issue by TingOOOgniT** [antvis/Graphin#357]
### Describe the bug

通过redux更新数据，报Error
Uncaught TypeError: Cannot assign to read only property 'style' of object '#<Object>'
尝试过通过实例方法去更新，也是一样的报错
尝试过设置的数据新拷贝一份，也一样报错

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

1. 点击图上的点进行点的编辑
2. 编辑完以后将数据推到redux store
3. Graphin实例收到数据变化，开始渲染
4. 报错

### Expected behavior

视图正常更新

### Screenshots or Videos

错误信息：
![image](https://user-images.githubusercontent.com/4090171/155974852-079ca628-3fd0-426e-ba34-2fb9fa8ebfe8.png)
代码位置：
![image](https://user-images.githubusercontent.com/4090171/155974904-3f86a6e3-78cf-4084-8135-bf72cb919a0f.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 98.0.4758.109（正式版本） (arm64)
- package版本信息
    "@ant-design/icons": "4.7.0",
    "@antv/g6": "^4.5.5",
    "@antv/graphin": "^2.4.15",
    "@antv/graphin-components": "^2.4.0",
    "@antv/graphin-icons": "^1.0.0",
    "@reduxjs/toolkit": "1.7.2",
    "antd": "4.18.2",
    "i18next": "21.6.5",
    "i18next-http-backend": "1.3.1",
    "lodash": "4.17.21",
    "react": "17.0.2",
    "react-color": "^2.19.3",
    "react-dom": "17.0.2",
    "react-i18next": "11.15.3",
    "react-redux": "7.2.3",
    "react-router-dom": "5.3.0",
    "react-scripts": "5.0.0",
    "sanitize.css": "13.0.0"

### Additional context

没有头绪为什么会报错，求给点思路。

**Comment by pomelo-nwu** [comment]
@TingOOOgniT Object.assign是浅拷贝，尝试用深拷贝试试，目前graphin内部的data和g6实例化后的data是同一个引用，所以如果是redux等用上了不可变数据方式，得深拷贝下

**Comment by TingOOOgniT** [comment]
使用了这些Behavior组件：
```
<ZoomCanvas />
<DragCanvas />
<ClickSelect />
<ResizeCanvas />
```
使用了以下graphin-components
Tooltip， Toolbar

**Comment by TingOOOgniT** [comment]
> @TingOOOgniT Object.assign是浅拷贝，尝试用深拷贝试试，目前graphin内部的data和g6实例化后的data是同一个引用，所以如果是redux等用上了不可变数据方式，得深拷贝下

@pomelo-nwu 我塞进去的数据，试过lodash的cloneDeep，也试过完全就写写一个对象把必要的值赋上去，但是还是一样的报错。就是很奇怪这个Object.assign为什么会不允许我更新对象，会error

**Comment by TingOOOgniT** [comment]
问题解决了。是因为我在点击时间的回调里面，把graph的一部分数据塞到了redux里面而没有用深拷贝。导致那一部分数据无法更新。
@pomelo-nwu 非常感谢你提供的信息。
