### ISSUE TITLE
首页图片被压缩

### ISSUE THREAD

**Issue by afc163** [antvis/Graphin#36]
**Describe the bug**

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/71395199-e2f1f100-264f-11ea-9656-4ba502dcdc2a.png">

**To Reproduce**

https://graphin.antv.vision/zh

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pomelo-nwu** [comment]
已处理图片压缩问题，不过依旧引入其他问题
- 1. 样式覆盖，原本的font和鼠标圈选的背景色可能被site中的antd样式覆盖
- 2.组件演示模块，需要优化。
这两个问题我重新提个issue处理
