### ISSUE TITLE
Setting edge as inactive does not change the opacity of edge labels (将边设为不活跃不会改变边标签的透明度)

### ISSUE THREAD

**Issue by dukesun99** [antvis/Graphin#363]
### Describe the bug

Setting edge as inactive does not change the opacity of edge labels. Please help to check if this is intended and if yes, any suggested directions to change it?
将边设为不活跃不会改变边标签的透明度。请帮忙查看下是否是一个预期中的行为，如果是，请问有什么建议的方法去更改这个行为呢？

### Your Example Website or App

https://codesandbox.io/s/loving-banach-zch3t?file=/App.tsx

### Steps to Reproduce the Bug or Issue

1. Enter the attached link
2. Hover mouse onto "路径-1" and "路径-2"

1. 进入上面的链接
2. 悬浮鼠标到"路径-1"和"路径-2"上

### Expected behavior

I expect to see the edge labels fade out along with the edges, and I see the edges fade out but label stays.
我期待看到边标签和边一起淡出，我实际看到边淡出但是标签保留不变。

### Platform

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.5.5
- Graphin 版本: 2.4.14

- OS: Windows
- Browser: Google Chrome
- G6 Version: 4.5.5
- Graphin Version: 2.4.14

### Additional context

Submitted [an issue](https://github.com/antvis/G6/issues/3514) in G6 repo and they think it is a Graphin component. 
在G6的repo下提交过[一个issue](https://github.com/antvis/G6/issues/3514)，但是他们回复认为是Graphin的部分。

Please suggest if possible which part of code is involved and I could submit a PR to fix it.
如果可以也请建议下改哪些code，我可以提一个PR去修。

**Comment by dukesun99** [comment]
Besides, [this official demo](https://codesandbox.io/s/e7rob) breaks from version 2.3.3 and onwards, but v2.3.2 works fine.
这个[官方的demo](https://codesandbox.io/s/e7rob)从2.3.3版本开始就不可以正常工作了，但2.3.2版本还可以。

**Comment by pomelo-nwu** [comment]
@dukesun99 Thanks for spotting the problem. I'll fix it later
![image](https://user-images.githubusercontent.com/10703060/159192448-32b0a31d-cc8c-4c28-bb3f-bac90dc4cd9a.png)

![image](https://user-images.githubusercontent.com/10703060/159192427-458ef326-0214-4621-a072-3dd5f563fcbe.png)

**Comment by pomelo-nwu** [comment]
@dukesun99 https://github.com/antvis/Graphin/pull/366    
Version [2.5.1](https://www.npmjs.com/package/@antv/graphin/v/2.5.1) is available

**Comment by dukesun99** [comment]
> Besides, [this official demo](https://codesandbox.io/s/e7rob) breaks from version 2.3.3 and onwards, but v2.3.2 works fine. 这个[官方的demo](https://codesandbox.io/s/e7rob)从2.3.3版本开始就不可以正常工作了，但2.3.2版本还可以。

@pomelo-nwu Thanks. This is another problem. And I checked this is not fixed in 2.5.1. Please also take a look! Thanks.

**Comment by dukesun99** [comment]
> > Besides, [this official demo](https://codesandbox.io/s/e7rob) breaks from version 2.3.3 and onwards, but v2.3.2 works fine. 这个[官方的demo](https://codesandbox.io/s/e7rob)从2.3.3版本开始就不可以正常工作了，但2.3.2版本还可以。
> 
> @pomelo-nwu Thanks. This is another problem. And I checked this is not fixed in 2.5.1. Please also take a look! Thanks.

I see... I read through the update log and the default hoverable is removed then. Just need to fix the demo.

**Comment by pomelo-nwu** [comment]
@dukesun99 https://github.com/antvis/Graphin/blob/master/packages/graphin/src/Graphin.tsx#L522 Yes, thanks for your PR
