### ISSUE TITLE
Layout is updated when a new node is added

### ISSUE THREAD

**Issue by Aycaa** [antvis/Graphin#386]
### Describe the bug

Hello,
We are using the Graphin library in our project. We add a node according to our scenario and the graphical layout is refreshed again. I'm losing my script that I used to work on canvas. The nodes I drag are shaped according to the order I specified in the graph library. How can I prevent this? I am attaching a sample screenshot of our application below. Thanks in advance for helping.
![1](https://user-images.githubusercontent.com/22319432/165629098-85d38e81-1d12-4059-998d-d165b98ef147.JPG)
![2](https://user-images.githubusercontent.com/22319432/165629101-963ab8d1-5752-4c60-a2a1-a09feb99a715.JPG)

**Sample code:**
let c =
        {
          id: id,
          label: "TEST",
          type: "graphin-circle",
          }
        };
        graph.addItem("node", c);
        graph.updateLayout("force");

### Expected behavior

I want node added without rearranging the canvas.

### Screenshots or Videos

![1](https://user-images.githubusercontent.com/22319432/165629563-ae9e14df-45cb-465f-948f-3ab941b03439.JPG)
![2](https://user-images.githubusercontent.com/22319432/165629565-941af50e-41eb-46b4-8323-6a40434fb97c.JPG)

**Comment by mix0000** [comment]
Use _**preset**_ layout type with specific X and Y positions.
