### ISSUE TITLE
Graphine out-of-canvas

### ISSUE THREAD

**Issue by Aycaa** [antvis/Graphin#387]
### Describe the bug

Hello, we are using the antvis graphine library in our project. When its nodes are dragged, it disappears off the canvas. I couldn't find out this in the documentation as well. We do not want nodes to go out of the canvas. How can we achieve this? Thanks in advance.

### Expected behavior

As a user, I don't want the nodes to disappear off the canvas.

### Screenshots or Videos

![tempsnip](https://user-images.githubusercontent.com/22319432/166889956-e8dce634-6506-405c-a171-9de3f1d70f5b.png)

**Comment by pomelo-nwu** [comment]
@Aycaa Can you give me a link to duplicate CodeSandbox？
