### ISSUE TITLE
内置的icon无法显示

### ISSUE THREAD

**Issue by hubl95** [antvis/Graphin#39]
我本地运行能正常显示节点里面的图标，然后编译发布到dev环境后图标就显示不出来了，是什么原因呢？

**Comment by hubl95** [comment]
![微信截图_20191225110234](https://user-images.githubusercontent.com/24307063/71430338-24dd6e80-2706-11ea-8a5b-c0cfed0b25f1.png)

**Comment by zxc0328** [comment]
![image](https://user-images.githubusercontent.com/10339692/71454710-f5de0000-27cc-11ea-9f1c-f3f464ebfa6c.png)

麻烦看一下开发者工具 Network 里面这个字体文件是否加载失败了
