### ISSUE TITLE
Feature：力导支持向心力配置

### ISSUE THREAD

**Issue by yohacai** [antvis/graphin#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pomelo-nwu** [comment]
graphin add `layout.force.centripetalOptions` to set centripetal force，you will check this demo for detail :  https://codesandbox.io/s/nice-bardeen-we0oe?fontsize=14&hidenavigation=1&theme=dark
