### ISSUE TITLE
Blank Graphin Tooltip in 2.6.0+ visible when not hovered

### ISSUE THREAD

**Issue by dukesun99** [antvis/Graphin#404]
### Describe the bug

A blank tooltip is visible when both height and width are specified in style. 

### Your Example Website or App

https://codesandbox.io/s/frosty-sid-gumy8w

### Steps to Reproduce the Bug or Issue

1. Just open the code and you will see a light blue box on the top left corner. 

### Expected behavior

I expect the tooltip is not visible when the node is not hovered.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 2.6.7

**Comment by dukesun99** [comment]
I suspect the code [here](https://github.com/antvis/Graphin/blob/32e4439e74166251dc4501f887faeb2e02db69d7/packages/graphin/src/components/Tooltip/getContainerStyles.tsx#L39) still leave a certain portion of the tooltip box in the screen, making it visible when not hovered. @pomelo-nwu

**Comment by dukesun99** [comment]
@pomelo-nwu Btw, the group chat QR code is expired? Possible to update one? Thanks.

**Comment by pomelo-nwu** [comment]
> @pomelo-nwu Btw, the group chat QR code is expired? Possible to update one? Thanks.

![image](https://user-images.githubusercontent.com/10703060/174510383-61d06397-8757-4eff-87df-44e8267ea778.png)

**Comment by pomelo-nwu** [comment]
It looks like the problem is [here](https://github.com/antvis/Graphin/blob/32e4439e74166251dc4501f887faeb2e02db69d7/packages/graphin/src/components/Tooltip/getContainerStyles.tsx#L39), can you pull a request?

**Comment by dukesun99** [comment]
> It looks like the problem is [here](https://github.com/antvis/Graphin/blob/32e4439e74166251dc4501f887faeb2e02db69d7/packages/graphin/src/components/Tooltip/getContainerStyles.tsx#L39), can you pull a request?

Done. Thanks.
