### ISSUE TITLE
关于Graphin组件里添加G6 timebar的实例

### ISSUE THREAD

**Issue by Redrain54** [antvis/Graphin#409]
### Describe the bug

因为想要使用交互的时间轴，所以我自定义了一个TimeBar组件，使用了G6的TimeBar实例，然后将其包裹在了<Graphin />组件内。结果一开始会在页面中正常显示时间轴，结果第二天莫名其妙的报错说“Cannot read properties of null(reading type)”，我查看了报错源码，是说在Timebar.prototype.filterData函数中的var type = this._cfgs.type有问题，简单说就是说我配置项的type属性取值为空，但我肯定有配置哇，并且我配置的是“simple”。
然后过了良久，到半夜它又自己好了……嗯，就比较崩溃
![微信图片_20220713000717](https://user-images.githubusercontent.com/62545114/178540661-3a6c2319-06bf-485b-a2d4-a219cd756adc.png)
![微信图片_20220713000722](https://user-images.githubusercontent.com/62545114/178540669-0c5bba59-c63d-48a9-ac48-901f1198d034.png)
![微信图片_20220713000729](https://user-images.githubusercontent.com/62545114/178540680-68d14779-e8ad-4771-9ef1-337f3ce3188a.png)
![微信图片_20220713000734](https://user-images.githubusercontent.com/62545114/178540683-dd7949d8-dc67-4143-8842-65c874823eb5.png)
![Uploading 1657642917335.jpg…]()

### Your Example Website or App

https://codesandbox.io/s/youthful-wood-36k7m3

### Steps to Reproduce the Bug or Issue

1.请先复制代码到IDE并引入Graphin G6等环境依赖
2.请运用模拟数据并呈现正常的Graphin图
3.隔一段时间刷新图的页面，就会产生报错；然后隔一段时间又会突然变好

### Expected behavior

![1657642917335](https://user-images.githubusercontent.com/62545114/178543686-5237d086-31b0-40ac-818d-7f7c010f6081.jpg)
产生如图所示的样子，在grapin展示图片的下方产生时间轴

### Platform

- OS: Windows（64bits）
- Browser:  Chrome
- Version:版本 103.0.5060.114（正式版本） （64 位）

**Comment by scarletfrank** [comment]
您好，这个问题您现在解决了吗？
我也遇到了类似问题，不过我是更改查询条件，加载下一次请求的时候，固定出现。

我在Timebar useEffect 处加了输出，一开始是正常进入hook里面渲染时间轴。
下一次请求的时候，数据还没加载好，就出现报错了。

会不会跟数据更新时，图更新机制有关？

我一把我自己包装的图组件一个ready设置成false，之后就调用Graph.destroy去了，之后就出现timebar的错误。

**Comment by Redrain54** [comment]
您好哇，我没能解决这个问题呢。确实因为不稳定，我最后换了一种实现方案。我看到之前关于timebar的这个issue里，官方有回复说会重新设计，所以我建议还是尽量别用了吧~我已经花了挺久时间在上面的，一直没成功我才提的issue，提完我也就没再研究啦~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/Graphin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 上午10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/Graphin] 关于Graphin组件里添加G6 timebar的实例 (Issue #409)





 
您好，这个问题您现在解决了吗？
 我也遇到了类似问题，不过我是更改查询条件，加载下一次请求的时候，固定出现。
 
我在Timebar useEffect 处加了输出，一开始是正常进入hook里面渲染时间轴。
 下一次请求的时候，数据还没加载好，就出现报错了。
 
会不会跟数据更新时，图更新机制有关？
 
我一把我自己包装的图组件一个ready设置成false，之后就调用Graph.destroy去了，之后就出现timebar的错误。

**Comment by scarletfrank** [comment]
> 您好哇，我没能解决这个问题呢。确实因为不稳定，我最后换了一种实现方案。我看到之前关于timebar的这个issue里，官方有回复说会重新设计，所以我建议还是尽量别用了吧~我已经花了挺久时间在上面的，一直没成功我才提的issue，提完我也就没再研究啦~
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "antvis/Graphin" ***@***.***&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 上午10:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [antvis/Graphin] 关于Graphin组件里添加G6 timebar的实例 (Issue #409) 您好，这个问题您现在解决了吗？ 我也遇到了类似问题，不过我是更改查询条件，加载下一次请求的时候，固定出现。 我在Timebar useEffect 处加了输出，一开始是正常进入hook里面渲染时间轴。 下一次请求的时候，数据还没加载好，就出现报错了。 会不会跟数据更新时，图更新机制有关？ 我一把我自己包装的图组件一个ready设置成false，之后就调用Graph.destroy去了，之后就出现timebar的错误。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

如果可以的话，您能简要分享下别的实现方案吗。（不用Graphin，直接React+G6吗 ）
等官方出TimeBar真不知道要等到啥时候

**Comment by Redrain54** [comment]
哈哈没有啦，我已经完全弃用了时间轴这个想法。我是根据我们项目的需求简化了一下，主要是实现根据时间进行不同演化的需要。所以我就直接用下拉框让用户选择时间，然后根据时间去处理数据并渲染到页面上，也算凑合着实现了根据时间演化的需求。（我那个项目不是公司里那种需要上线或者要求比较高的工程，所以就把需求简化了一下）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/Graphin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/Graphin] 关于Graphin组件里添加G6 timebar的实例 (Issue #409)





  
您好哇，我没能解决这个问题呢。确实因为不稳定，我最后换了一种实现方案。我看到之前关于timebar的这个issue里，官方有回复说会重新设计，所以我建议还是尽量别用了吧我已经花了挺久时间在上面的，一直没成功我才提的issue，提完我也就没再研究啦
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "antvis/Graphin" @.&gt;; 发送时间:&nbsp;2022年8月19日(星期五) 上午10:21 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [antvis/Graphin] 关于Graphin组件里添加G6 timebar的实例 (Issue #409) 您好，这个问题您现在解决了吗？ 我也遇到了类似问题，不过我是更改查询条件，加载下一次请求的时候，固定出现。 我在Timebar useEffect 处加了输出，一开始是正常进入hook里面渲染时间轴。 下一次请求的时候，数据还没加载好，就出现报错了。 会不会跟数据更新时，图更新机制有关？ 我一把我自己包装的图组件一个ready设置成false，之后就调用Graph.destroy去了，之后就出现timebar的错误。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
如果可以的话，您能简要分享下别的实现方案吗。（不用Graphin，直接React+G6吗 ）
 等官方出TimeBar真不知道要等到啥时候

**Comment by pomelo-nwu** [comment]
@scarletfrank @Redrain54 可以使用基于Graphin的时间轴组件，官方实现的：https://github.com/antvis/G6VP/pull/301
https://github.com/antvis/G6VP/issues/294
