### ISSUE TITLE
依赖的版本有问题

### ISSUE THREAD

**Issue by lavyun** [antvis/Graphin#433]
### Describe the bug

依赖的版本有问题
![image](https://user-images.githubusercontent.com/22797898/186637386-ee2f0073-5c9c-489e-8982-1efe4d7fe4e5.png)
![image](https://user-images.githubusercontent.com/22797898/186638064-2b668fc1-5378-4284-8ca1-00fb570ed875.png)

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

1

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by pomelo-nwu** [comment]
@lavyun 已经发布解决了，详见PR #434 ，现在最新版本为：https://www.npmjs.com/package/@antv/graphin/v/2.7.8
