### ISSUE TITLE
网站菜单色彩问题

### ISSUE THREAD

**Issue by afc163** [antvis/Graphin#44]
**Describe the bug**

<img width="787" alt="image" src="https://user-images.githubusercontent.com/507615/71569959-8f7b1980-2b0d-11ea-99e2-0eb8bc0c4070.png">

**To Reproduce**

Visit：https://graphin.antv.vision/zh/examples/render/save

**Expected behavior**

应该和其他站点一样是紫色主色。

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by afc163** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/507615/71709214-d8461180-2e30-11ea-991e-99a20aedb516.png">

应该是同一个问题。

**Comment by afc163** [comment]
没人啊

**Comment by pomelo-nwu** [comment]
graphin-site中多引入了antd的样式，覆盖了antv主题的antd样式：https://github.com/antvis/Graphin/blob/master/packages/graphin-site/gatsby-browser.js#L13
我改下重新部署
