### ISSUE TITLE
渲染大于100个节点时就会很慢

### ISSUE THREAD

**Issue by xichao520** [antvis/Graphin#442]
### Describe the bug

使用官方demo（https://graphin.antv.vision/components/built-in/legend） 模拟多节点情况的渲染性能时，发现mock一百个节点以上时就会很慢

### Your Example Website or App

https://codesandbox.io/s/hmwwxw?file=/App.tsx

### Steps to Reproduce the Bug or Issue

1.修改mock节点数量为100，观察渲染性能

### Expected behavior

期望能立即看到渲染结果

### Platform

- OS: [ Windows ]
- Browser: [Chrome]
- Version: [105.0.5195.127]

**Comment by scarletfrank** [comment]
我也遇到了性能问题，我也想在这个issue下面讨论下。就是大概Graphin在电脑性能不太行的情况下，还有优化可能吗？

## Describe the bug

我自行定义了“一键拓展”的功能，一次增加一百多个节点（甚至更多）。现在发现这个一键拓展功能，如果电脑的性能不足的话，渲染出的图形就会错位，即部分节点不会移动到正确位置（我已经关掉了动画效果）

## Your Example Website or App

我内网环境访问不到楼主写的Sandbox，我是自己开发的项目遇到这个问题。

## Steps to Reproduce the Bug or Issue

1. 点击一键拓展功能，在远程桌面/堡垒机电脑上出现错位问题（Win7），我看了CPU都不咋地。之前跟运维讨论，他说应该是没硬件加速的。
2. 我自己电脑 R7 5800H 不带独显的笔记本，开不开硬件加速，访问应用都是流畅的，当然开了硬件加速感觉更快一点

大致截图可以往下看。在拓展之后，一个绿色密集簇中间是空的，正常就是那个密集节点要在中心的。

## Screentshots or Videos

![image](https://user-images.githubusercontent.com/25702099/207004564-887e0c30-6e4d-409f-a5a1-fd869dc11754.png)

## Platform

- OS : [Windows]
- Browser: [Chrome]
- Version: [94/105]

## Additional Context

None

**Comment by xichao520** [comment]
建议使用G6代替Graphin

**Comment by scarletfrank** [comment]
> 建议使用G6代替Graphin

哈哈哈，我之前是有计划用G6写，内部有个框架是Ant Design Vue的，必须转用G6。我现在就怕拿G6写了，到最后生产那些堡垒机还是带不动。想确定下是我写法问题呢，还是框架本身（不管是Graphin还是G6），有对性能的最低要求。

而且我发现就是第一次渲染完成的时候会错位，等渲染完边和节点，位置没调整好就停了。
但通过按钮手动再次开关动画效果，还是能移动到正确的位置（虽然会卡一点）
