### ISSUE TITLE
2.7.10 verision don't contain dist dir

### ISSUE THREAD

**Issue by lhz960904** [antvis/Graphin#447]
### 2.7.9 

<img width="286" alt="image" src="https://user-images.githubusercontent.com/29157111/192094119-3619b933-82db-4713-8f65-47c895f71fda.png">

### 2.7.10
<img width="273" alt="image" src="https://user-images.githubusercontent.com/29157111/192094136-c519c0b3-21e5-45b6-bdde-7302816d3415.png">

### Your Example Website or App

nothing

### Steps to Reproduce the Bug or Issue

update npm package 2.7.10

### Expected behavior

Minor version changes should not has break change

### Platform

- OS: macOS
- Version: 2.7.10

**Comment by pomelo-nwu** [comment]
@lhz960904 已经解决
