### ISSUE TITLE
npm 安装的graphin-components有问题

### ISSUE THREAD

**Issue by FrankBGao** [antvis/Graphin#45]
引入的时候没有样式。
不npm安装，直接用源码是可以的。

**Comment by zxc0328** [comment]
请问是否引入了 css 文件呢：

import '@antv/graphin-components/dist/index.css';

**Comment by FrankBGao** [comment]
我是在antd pro上用的，直接import不行，文档要import style from 'index.css'

**Comment by zxc0328** [comment]
import style from '@antv/graphin-components/dist/index.css' 这样 css module 的形式也是支持的。具体怎么引入看构建工具的配置。
