### ISSUE TITLE
GraphInsight无法打开github页面

### ISSUE THREAD

**Issue by mollylanguange** [antvis/Graphin#453]
### Describe the bug

GraphInsight无法打开github页面

### Your Example Website or App

https://github.com/antvis/GraphInsight

### Steps to Reproduce the Bug or Issue

在页面https://graphinsight.antgroup.com/home.html#/点击github后页面打不开，显示４０４．无法找到相关资源

### Expected behavior

希望在页面https://graphinsight.antgroup.com/home.html#/点击github后页面转到相关的github页面

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by pomelo-nwu** [comment]
在做开源前的准备，仓库转为 Private 了 
![image](https://user-images.githubusercontent.com/10703060/194784269-d87ae867-080b-4411-8957-35b5d30709f4.png)

**Comment by mollylanguange** [comment]
感谢回答，大概什么时候开源呢？

**Comment by pomelo-nwu** [comment]
> 感谢回答，大概什么时候开源呢？

2022.11.22 AntV 开源日当天
