### ISSUE TITLE
import { Statistic } from '@antv/graphin-components'; 找不到

### ISSUE THREAD

**Issue by liuyanhe96** [antvis/Graphin#473]
### Describe the bug

import { Statistic } from '@antv/graphin-components'; 找不到 "@antv/graphin-components": "^2.4.0",

### Your Example Website or App

import { Statistic } from '@antv/graphin-components'; 找不到

### Steps to Reproduce the Bug or Issue

import { Statistic } from '@antv/graphin-components'; 找不到

### Expected behavior

import { Statistic } from '@antv/graphin-components'; 找不到

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by pomelo-nwu** [comment]
@liuyanhe96 Statistic 并没有实现。
想了解更多分析组件，推荐你查看这个平台：https://insight.antv.antgroup.com/#/open/assets-list?assetKey=FilterPanel 它是基于 Graphin 构建的分析平台，或许能给你一些帮助
