### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'manipulateBehaviors')     at AbstractGraph.removeBehaviors (graph.js:588:1)

### ISSUE THREAD

**Issue by Faker-lz** [antvis/Graphin#474]
### Describe the bug

When I used the G6 Graph in react project, I got the error in `@antv/g6-core/es/graph/graph.js` 

### Your Example Website or App

https://github.com/Faker-lz/sbom

### Steps to Reproduce the Bug or Issue

I found an error to the following code according to the browser's console:
```
  /**
   * 移除行为
   * @param {string | ModeOption | ModeType[]} behaviors 移除的行为
   * @param {string | string[]} modes 从指定的模式中移除
   * @return {Graph} Graph
   */
  AbstractGraph.prototype.removeBehaviors = function (behaviors, modes) {
    var modeController = this.get('modeController');
    modeController.manipulateBehaviors(behaviors, modes, false);
    return this;
  };
```

### Expected behavior

Is there anyone who is having the same problem as me and I would like help

### Platform

- OS: Windows
- Browser: EDGE
- Version: ["@antv/g6": "4.7.10",
    "@antv/gi-assets-advance": "1.1.1",
    "@antv/gi-assets-algorithm": "1.0.0",
    "@antv/gi-assets-basic": "1.3.0",
    "@antv/gi-assets-graphscope": "1.0.2",
    "@antv/gi-assets-neo4j": "1.1.2",
    "@antv/gi-assets-scene": "1.0.0",
    "@antv/gi-assets-tugraph": "1.1.0",
    "@antv/gi-sdk": "1.2.0",
    "@antv/gi-theme-antd": "0.3.0",
    "@antv/graphin": "2.7.13",]

**Comment by janwirth** [comment]
I'm experiencing the same problem. Did you find a solution @Faker-lz

**Comment by Faker-lz** [comment]
Yes, I just used
```
ReactDOM.render(  <React.StrictMode>
    <App />
</React.StrictMode>, document.getElementById('root'))
```
to replace the official demo code:
```
const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
I think the error ascribes React's version.

**Comment by janwirth** [comment]
Thank you! So the solution is to run graphin inside a strict mode component. Interesting!

**Comment by gaomAndximi** [comment]
At the beginning, the version of react18 was used, and now the version has been reduced to 16.13.1. Now no errors are shown.

**Comment by bobony** [comment]
I am also experiencing the same problem I am using react18.2.0. Any luck?

**Comment by bobony** [comment]
if anyone facing issue run your app without React.StrictMode it works

**Comment by Zhuoda1** [comment]
> if anyone facing issue run your app without React.StrictMode it works

Thanks! Problem fixed.

**Comment by Yanyan-Wang** [comment]
Duplicated to https://github.com/antvis/Graphin/issues/476
