### ISSUE TITLE
Tooltip positioning error in custom nodes

### ISSUE THREAD

**Issue by AhmedSalihCezayir** [antvis/Graphin#485]
### Describe the bug

When a tooltip is added to a custom node, tooltip is not centered with respect to the node but instead it is in the wrong position.

### Your Example Website or App

https://codesandbox.io/s/tooltip-location-problem-morw7v?file=/src/App.js

### Steps to Reproduce the Bug or Issue

1. Go to the sandbox that I provided.
2. See the tooltip positioning problem.

### Expected behavior

I expect the tooltip to be centered.

### Screenshots or Videos

Current tooltip positioning:
![image](https://github.com/antvis/Graphin/assets/63608956/11a00520-8ba1-40a4-bf29-42b7c043ce53)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by pomelo-nwu** [comment]
@AhmedSalihCezayir Since the tooltip display position is the center of the default CircleNode：https://github.com/antvis/Graphin/blob/master/packages/graphin/src/components/Tooltip/useTooltip.tsx#L51

it is recommended that you customize a tooltip for this case
