### ISSUE TITLE
G6的Option，传入没有效果

### ISSUE THREAD

**Issue by FrankBGao** [antvis/Graphin#49]
https://graphin.antv.vision/zh/docs/api/graphin#options
说，“另外，这个 props.options 也支持传入 G6 的 Options。详见 G6 Options。”
但是，g6的option，fitView，autoPaint:true传入没有效果。
    <Graphin data={transform(import_data)}
             options = {{pixelRatio :100, keyShapeZoom:0.001, fitView:true,  autoPaint:true}}
             layout={{
               name: "dagre",
               options: {
                 center: [window.innerWidth / 3, window.innerHeight / 3], // 可选，中心点坐标
                 nodeSize: [15, 15], // 可选，节点大小
                 nodesep: 12, // 可选, 节点水平间距(px)
                 ranksep: 15, // 可选, 每一层节点之间间距
                 align: "UL", // 可选, 放置位置
                 rankdir: 'LR',
               }
             }}>

**Comment by iventong** [comment]
我也遇到这样的问题，使用svg 渲染不起作用 在G6里可以的，说明配置没有传递

**Comment by FrankBGao** [comment]
fitView 可以传入，传入后也生效。但是传入后Highlight，Drag，Zoom无效。
代码如下
[GraphinTest.zip](https://github.com/antvis/Graphin/files/4204497/GraphinTest.zip)
