### ISSUE TITLE
graphin-circle node with badges type image cannot work with offset

### ISSUE THREAD

**Issue by DustarMao** [antvis/Graphin#507]
### Describe the bug

see example: badge-circle and image are not in same position when set offset

### Your Example Website or App

https://codesandbox.io/embed/silly-browser-pf9hfw?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce the Bug or Issue

see example

### Expected behavior

badge image should in badge circle

### Screenshots or Videos

![image](https://github.com/antvis/Graphin/assets/7754813/1bb105eb-a094-426e-a1b2-6d095b9e50d9)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by pomelo-nwu** [comment]
@DustarMao thanks for your contribution ～
