### ISSUE TITLE
官网文档里的demo报错

### ISSUE THREAD

**Issue by cuidingfeng** [antvis/Graphin#511]
### Describe the bug

用官网这个demo<https://graphin.antv.vision/graphin/layout/leaf-cluster/>，在本地运行时js会报错，demo的代码什么也没有改。
报错信息是：
Uncaught TypeError: Cannot set properties of null (setting 'width')
at AbstractGraph2.set (graph.js:293:19)

### Your Example Website or App

https://github.com/cuidingfeng/transaction-analysis/blob/main/src/pages/Home/charts.tsx

### Steps to Reproduce the Bug or Issue

1、yarn dev本地启动
2、本地访问：http://localhost:5173/home
3、改变窗口大小，触发resize

### Expected behavior

正常应该js不报错，并且画中的节点可以点击交互

### Screenshots or Videos

![image](https://github.com/antvis/Graphin/assets/2821160/64189cf2-2ead-4068-86a6-f63ceec066e1)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 116.0.5845.96（正式版本） (arm64)

**Comment by pomelo-nwu** [comment]
@cuidingfeng 好的，我clone你的项目试试

**Comment by pomelo-nwu** [comment]
@cuidingfeng 我测试了下，发现是 react 版本的问题，Graphin2.x 版本不支持 react 18。我在你的项目仓库中，将react版本降级为17.x 就可以正常运行

**Comment by cuidingfeng** [comment]
可以了，非常感谢

**Comment by cuidingfeng** [comment]
用react17，一切正常了

**Comment by cuidingfeng** [comment]
用react17，一切正常了，非常感谢

**Comment by cuidingfeng** [comment]
用react17，一切正常了，非常感谢
