### ISSUE TITLE
Graphin V3 如何注册自定义节点

### ISSUE THREAD

**Issue by gravese** [antvis/Graphin#539]

**Comment by hustcc** [comment]
直接沿用 G6 5.0 的 api 级了，新版本的 Graphin 没有增加新概念和 API 。

**Comment by liaodalin19903** [comment]
> 直接沿用 G6 5.0 的 api 级了，新版本的 Graphin 没有增加新概念和 API 。

@hustcc  请问您的意思是什么呢？如何在Graphin中注册自定义节点呢？

**Comment by hustcc** [comment]
你具体需求是什么？

- 如果是自定义节点，参考：https://g6.antv.antgroup.com/manual/custom-extension/element

然后注册节点：

```ts
mport { register, ExtensionCategory } from '@antv/g6';
import { CustomNode } from 'package-name/or/path-to-your-custom-node';

register(ExtensionCategory.NODE, 'custom-node', CustomNode);
```

在 Graphin 中就可以使用这个 type = 'custom-node' 了。

- 如果是需要用 React 去写节点，可以参考：https://github.com/antvis/G6/tree/v5/packages/g6-extension-react
