### ISSUE TITLE
这个产品还会继续更新维护吗？

### ISSUE THREAD

**Issue by Rey-Wang** [antvis/Graphin#541]
有这个疑问主要来自于以下几点
-  AntV 的官网产品列表中没有 Graphin （https://antv.antgroup.com/）
- Graphin 的官方文档已经很久没有更新
- Issue 列表已经很久没人回复

**Comment by yvonneyx** [comment]
Graphin 依旧作为 G6 周边生态的重要一环。但后续不会在 AntV 的官网产品中展示，也不会建设专门的文档站点，相关指南都会写在 README 中。

既 6.6 发布 G6 5.0 后，Graphin 3.0 正式版也已发布，可以直接安装使用。GISDK 正在开发中，预计八月上半旬发布。非常推荐对现有库进行升级，体验更轻更强的 G6 💪

关于 Graphin 2.0 非重大功能缺陷外的 Issue，官方不再投入处理，但依旧鼓励社区提 pr 解决~
