### ISSUE TITLE
TypeError: Cannot read property 'Marker' of undefined

### ISSUE THREAD

**Issue by Malcn** [antvis/Graphin#55]
package.json
{
  "name": "data-driven",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "main": "src/index.js",
  "dependencies": {
    "@antv/graphin": "1.0.3",
    "antd": "3.25.2",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.3.1"
  },
  "devDependencies": {
    "typescript": "3.7.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}

版本1.0.3，1.0.2运行报错，把@antv/graphin版本降到1.0.1好了

**Comment by budlion** [comment]
这是由于@antv/graphin暂时不兼容 @antv/g6@3.3 导致的。可以把@antv/g6版本限制在 ~3.2。兼容性问题会在下个版本解决
