### ISSUE TITLE
[question] 请问什么是`图可视化场景`和`图分析场景`？ 

### ISSUE THREAD

**Issue by liaodalin19903** [antvis/Graphin#551]
根据集成到项目中的深度不同，提供库：Graphin和GI-SDK
图可视化场景：Graphin
图分析场景：GI-SDK

请问什么是`图可视化场景`和`图分析场景`？

**Comment by hustcc** [comment]
- 图可视化场景，就是给一份数据，用可视化展示出来，主要关注在画布那一部分。
- 图分析应用场景，就是需要构建一个应用包含的内容，包含有画布、工具栏、菜单、以及其他的联动区域等等。

下者包含上者，所以 GI-SDK 也是依赖于 Graphin 的。

**Comment by hustcc** [comment]
![image](https://github.com/user-attachments/assets/8102cbb0-5913-42fe-ac40-f84056960fa1)
