### ISSUE TITLE
[question] 请问想要使用gi-sdk进行数据的展示，我想要自定义node的样式，这里如何进行定义呢？

### ISSUE THREAD

**Issue by liaodalin19903** [antvis/Graphin#554]
比如想要：
将圆点定义为类图的样式：

默认圆点样式：
![QQ_1727800063471](https://github.com/user-attachments/assets/ee3a53c6-f6ab-455b-9c1e-141af712478f)

类图的自定义节点和边：
![QQ_1727799994471](https://github.com/user-attachments/assets/a34d8ead-8f82-4c00-8b5b-052e2d22253a)

**Comment by yvonneyx** [comment]
建议用 React Node 来实现，可以参考 https://g6.antv.antgroup.com/examples/element/custom-node#react-node
