### ISSUE TITLE
[question] 安装了@antv/gi-sdk之后，不能像docs官方测试项目里面一样引入使用。

### ISSUE THREAD

**Issue by liaodalin19903** [antvis/Graphin#555]
比如在引用：`type { Application } `的时候：
```
import type { Application } from '@antv/gi-sdk';
```

报错：
```
模块 ""@antv/gi-sdk"" 没有导出的成员 "Application"。你是想改用 "import Application from "@antv/gi-sdk"" 吗?ts(2614)
```
![QQ_1727837713613](https://github.com/user-attachments/assets/1524ca4f-eecb-4515-8d5a-bd70c1b8e665)

===

package.json:
```
  "dependencies": {
    "@antv/g6": "^5.0.25",
    "@antv/gi-sdk": "^2.4.23",
    "antd": "^5.21.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
```

**Comment by hustcc** [comment]
> import type { Application } from '@antv/gi-sdk';

这个用法是从哪里看的？

**Comment by liaodalin19903** [comment]
> import type { Application } from '@antv/gi-sdk';

 [这里](https://github.com/antvis/Graphin/blob/00bc85eaa4196ecc2974dcaa98d9bb14117d51ef/packages/gi-sdk/docs/config.ts#L1)， 可能版本改变了。

**Comment by yvonneyx** [comment]
3.0.0 正式版本已发布，欢迎使用 ❤️
