### ISSUE TITLE
Cannot add custom G6 interaction mode

### ISSUE THREAD

**Issue by totogo** [antvis/Graphin#62]
**Describe the bug**
When passing register to Graphin props, custom G6 mode cannot be initiated as expected. 

```JavaScript
  const register = {
    behavior: (G6: G6Type): BehaviorRegister[] => [
      {
        mode: 'edit', // Custom mode
        options: {},
        name: 'click-add-node',
        register: (G6: G6Type) => {
          G6.registerBehavior('click-add-node', clickAddNodeBehvavior);
        },
      },
    ],
  };
```

**Additional context**
The issue could be solved by allowing additional modes in this piece of code: 
https://github.com/antvis/Graphin/blob/3425139eef700a10723d5533424de5479fee001a/packages/graphin/src/controller/init.ts#L115-L117

**Comment by pomelo-nwu** [comment]
mode最早的设计是做事件隔离，做编辑状态和普通状态的切换，g6目前专注做图分析， 图编辑已经慢慢弱化，mode模式在上层graphin的图组件里，可以考虑做个兼容处理。
