### ISSUE TITLE
Graphin components missing after toggle full screen

### ISSUE THREAD

**Issue by nylqd** [antvis/Graphin#66]
**Describe the bug**
Graphin studio count and toolbar missing in full screen mode.

**To Reproduce**

https://codesandbox.io/s/twrb3

**Expected behavior**
Graphin studio count and toolbar show as normal.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 80.0.3987.149

**Comment by pomelo-nwu** [comment]
Known bugs, fixed in next release

**Comment by pomelo-nwu** [comment]
https://graphin.antv.vision/zh/examples/components/toolbar
