### ISSUE TITLE
dagre传入G6的defaultEdge参数无效

### ISSUE THREAD

**Issue by laolaolulu** [antvis/Graphin#73]
<Graphin
        data={data2}
        options={{
          fitView: true,
          defaultEdge: {
            shape: 'polyline',
            style: {
              radius: 20,
              offset: 45,
              endArrow: true,
              lineWidth: 2,
              stroke: '#C2C8D5'
            },
          }
        }}
        layout={{
          name: "dagre",
          options: {

            // rankdir: 'RL',
            //height: 'calc(100vh - 100px)'
          }
        }}
        register={{
          edgeShape: (G6: G6Type) => [{
            name: "line-polyline",
            register: () => {
              const dashArray = [
                [0, 1],
                [0, 2],
                [1, 2],
                [0, 1, 1, 2],
                [0, 2, 1, 2],
                [1, 2, 1, 2],
                [2, 2, 1, 2],
                [3, 2, 1, 2],
                [4, 2, 1, 2],
              ];

              const lineDash = [4, 2, 1, 2];
              const interval = 9; // lineDash 的和
              G6.registerEdge("line-polyline", {
                afterDraw(cfg: any, group: any) {
                  // 获得该边的第一个图形，这里是边的 path
                  const shape = group.get('children')[0];
                  // 获得边的 path 的总长度
                  const length = shape.getTotalLength();
                  let totalArray: Array<number> = [];
                  // 计算出整条线的 lineDash
                  for (let i = 0; i < length; i += interval) {
                    totalArray = totalArray.concat(lineDash);
                  }

                  let index = 0;
                  // 边 path 图形的动画
                  shape.animate({
                    // 动画重复
                    repeat: true,
                    // 每一帧的操作，入参 ratio：这一帧的比例值（Number）。返回值：这一帧需要变化的参数集（Object）。
                    onFrame() {
                      const cfg = {
                        lineDash: dashArray[index].concat(totalArray)
                      };
                      // 每次移动 1
                      index = (index + 1) % interval;
                      // 返回需要修改的参数集，这里只修改了 lineDash
                      return cfg;
                    }
                  }, 3000);  // 一次动画的时长为 3000
                }
              }, 'polyline')  // 详见 G6 registerEdge 文档
            }
          }]
        }}

      ></Graphin>

**Comment by pomelo-nwu** [comment]
Graphin1.x版本和G6的机制不一样，这些问题在2.0解决了：https://github.com/antvis/Graphin/blob/master/packages/graphin/src/Graphin.tsx#L211

**Comment by pomelo-nwu** [comment]
@laolaolulu 2.0版本解决这个问题，参考文档：https://graphin.antv.vision/graphin/render/edge
