### ISSUE TITLE
antd v4 update

### ISSUE THREAD

**Issue by florianwiech** [antvis/Graphin#94]
Hi everyone,
can we update ant design to version 4 in the following packages:
- graphin-components
- graphin-studio

[Migration v4](https://ant.design/docs/react/migration-v4)

As far as I can spot it, the handling of Icons needs an update.
Two approaches:
1. The use of `import { Icon } from '@ant-design/compatible';`. Only the imports must be changed.
2. The use of the new `@ant-design/icons` package with the ability to use any other icon library. This means that some components need a redesign and the component props might change.

What are your thoughts? :)

**Comment by CrazyOctopusDan** [comment]
现在的graphin-components里面依赖的antd是v3.25
我使用的umi框架携带的antd是v4.0
![image](https://user-images.githubusercontent.com/18019209/80463234-8179c000-896a-11ea-98c9-7902630e35c2.png)
打包的时候就会出现这样的问题↑

解决方法是自己再手动装一个3.25的antd版本，
但是其中的popover等的样式又丢失了！

**Comment by pomelo-nwu** [comment]
升级已经做了，详见[#98](https://github.com/antvis/Graphin/pull/98),刚才发布了npm包，升级graphin-components@[1.2.1](https://www.npmjs.com/package/@antv/graphin-components/v/1.2.1)即可

**Comment by pomelo-nwu** [comment]
> Hi everyone,
> can we update ant design to version 4 in the following packages:
> 
> * graphin-components
> * graphin-studio
> 
> [Migration v4](https://ant.design/docs/react/migration-v4)
> 
> As far as I can spot it, the handling of Icons needs an update.
> Two approaches:
> 
> 1. The use of `import { Icon } from '@ant-design/compatible';`. Only the imports must be changed.
> 2. The use of the new `@ant-design/icons` package with the ability to use any other icon library. This means that some components need a redesign and the component props might change.
> 
> What are your thoughts? :)

Graphin-components and graphin-studio have been upgraded to antd 4.0 (PR [# 98](https://github.com/antvis/Graphin/pull/98)), please update graphin-components to version 1.2.1

**Comment by florianwiech** [comment]
Thank You!
